Repository kubevirt/ssp-operator, pull requests merged in 2020-11, with the labels that each got.

#20 Add NodeLabeller Operand to the new ssp operator.
  api/v1alpha1/ssp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/samples/ssp_v1alpha1_ssp.yaml
  controllers/ssp_controller.go
  internal/common/environment.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/node-labeller/reconcile_test.go
  internal/operands/node-labeller/resources.go
  tests/nodeLabeller_test.go
  tests/tests_suite_test.go
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/doc.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/legacy.go
  vendor/github.com/openshift/api/security/v1/register.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#28 Added missing webhook testid
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#30 Fix expected error message in webhook functional test
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#31 Add validations to the API and webhook
  api/v1alpha1/ssp_types.go
  api/v1alpha1/ssp_webhook.go
  api/v1alpha1/ssp_webhook_test.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#23 Add status phase and conditions
  controllers/ssp_controller.go
  go.mod
  internal/common/cache.go
  internal/common/request.go
  internal/common/resource.go
  internal/common/resource_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/node-labeller/reconcile_test.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  tests/commonTemplates_test.go
  tests/metrics_test.go
  tests/nodeLabeller_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  tests/watcher.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#29 Update Dockerfile and add RBAC rules needed to run operator in cluster
  Dockerfile
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/ssp_controller.go
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/template-validator/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#34 Reconcile the exact same resources as the old operator
  internal/operands/template-validator/resources.go
  tests/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#36 Makefile uses 'oc' or 'kubectl' depending on which one is available
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#33 Add test ids
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#35 added csv-generator
  .gitignore
  .travis.yml
  Dockerfile
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ssp-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  hack/csv-generator.sh
  hack/update-csv.py
  tests/test-csv-generator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#40 [FIX] add missing divider between deployment and crds
  hack/csv-generator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#41 Functests wait for operator deployment
  Makefile
  internal/common/environment.go
  tests/tests_suite_test.go
  tests/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#39 Bump controller-gen and dependencies
  Makefile
  api/v1alpha1/ssp_webhook.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/crd/patches/cainjection_in_ssps.yaml
  config/crd/patches/webhook_in_ssps.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.v1beta1.yaml
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#46 Release container and manifests on tag
  .travis.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#43 Change default namespace for operator pod
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/webhook/manifests.v1beta1.yaml
  config/webhook/service.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
