Repository kubevirt/ssp-operator, pull requests merged in 2020-10, with the labels that each got.

#13 Use controller runtime methods
  controllers/ssp_controller.go
  internal/common/resource.go
  internal/common/resource_test.go
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  tests/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#19 Do not watch the same resource multiple times
  controllers/ssp_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#18 Update README.md with instructions how to run tests
  Makefile
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#16 Use API from controller-lifecycle-operator-sdk
  api/v1alpha1/ssp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  go.mod
  go.sum
  internal/operands/template-validator/reconcile.go
  tests/validator_test.go
  vendor/github.com/go-logr/zapr/Gopkg.lock
  vendor/github.com/go-logr/zapr/Gopkg.toml
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/golang.org/x/mod/LICENSE
  vendor/golang.org/x/mod/PATENTS
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#21 Temporarily skip build container
  Makefile
  README.md
  controllers/ssp_controller.go
  internal/operands/template-validator/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#22 Create interface for operands
  controllers/ssp_controller.go
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#17 Add common-templates operand to SSP Operator
  .gitignore
  Makefile
  api/v1alpha1/ssp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  controllers/ssp_controller.go
  data/common-templates-bundle/common-templates-v0.12.2.yaml
  go.mod
  go.sum
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.12.2.yaml
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/common-templates/resource.go
  tests/commonTemplates_test.go
  tests/tests_suite_test.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/pkg/serialization/serialization.go
  vendor/github.com/openshift/api/template/v1/codec.go
  vendor/github.com/openshift/api/template/v1/consts.go
  vendor/github.com/openshift/api/template/v1/doc.go
  vendor/github.com/openshift/api/template/v1/generated.pb.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/api/template/v1/legacy.go
  vendor/github.com/openshift/api/template/v1/register.go
  vendor/github.com/openshift/api/template/v1/types.go
  vendor/github.com/openshift/api/template/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/template/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL
