Repository kubevirt/ssp-operator, pull requests merged in 2020-12, with the labels that each got.

#52 Add scripts to deploy kubevirt, cdi and the old operator
  hack/deploy-kubevirt-and-cdi.sh
  hack/deploy-old-ssp-operator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#53 Add LICENSE file
  LICENSE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#49 Run functional tests with existing SSP CR
  tests/commonTemplates_test.go
  tests/metrics_test.go
  tests/nodeLabeller_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#42 Pause kubevirt-ssp-operator CRs on reconciliation
  config/rbac/role.yaml
  controllers/ssp_controller.go
  go.sum
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  tests/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#54 Increase API version to v1beta1
  PROJECT
  README.md
  api/v1beta1/groupversion_info.go
  api/v1beta1/ssp_types.go
  api/v1beta1/ssp_webhook.go
  api/v1beta1/ssp_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/manifests/bases/ssp-operator.clusterserviceversion.yaml
  config/samples/kustomization.yaml
  config/samples/ssp_v1beta1_ssp.yaml
  config/webhook/manifests.v1beta1.yaml
  controllers/ssp_controller.go
  controllers/suite_test.go
  data/crd/ssp.kubevirt.io_ssps.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/common/request.go
  internal/common/resource_test.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/node-labeller/reconcile_test.go
  internal/operands/template-validator/reconcile_test.go
  main.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  tests/watcher.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#55 Validate that namespace for common templates exists
  api/v1beta1/ssp_webhook.go
  api/v1beta1/ssp_webhook_test.go
  tests/tests_suite_test.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#56 Made some CR fields optional and set defaults for the optional fields
  api/v1beta1/ssp_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/samples/ssp_v1beta1_ssp.yaml
  internal/common/environment.go
  internal/operands/node-labeller/defaults.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/node-labeller/resources.go
  internal/operands/template-validator/defaults.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  tests/tests_suite_test.go
  tests/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#57 Change resource names used by operator
  Makefile
  api/v1beta1/ssp_webhook.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ssp-operator.clusterserviceversion.yaml
  config/namespace/kustomization.yaml
  config/namespace/namespace.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/samples/ssp_v1beta1_ssp.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.v1beta1.yaml
  config/webhook/service.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#60 Remove unit tests from TravisCI
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#58 Regenerate data/crd
  data/crd/ssp.kubevirt.io_ssps.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#59 Break infinite reconciliation loop
  controllers/ssp_controller.go
  internal/common/cache.go
  internal/common/request.go
  internal/common/resource.go
  internal/common/resource_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#61 Bump template-validator
  go.sum
  internal/operands/template-validator/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#64 Update the common-templates bundle to v0.13.0-rc.0
  data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml
  internal/operands/common-templates/resource.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#65 Update common template bundle
  data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#66 Fixed operator version assignment
  controllers/ssp_controller.go
Labels: approved, dco-signoff: yes, release-note-none, size/XS

#63 Add test ensuring one default template per OS
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/M

#69 Add missing upgrade testid
  tests/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#67 Fix CSV for OLM deployments
  .gitignore
  Makefile
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  main.go
Labels: dco-signoff: yes, release-note-none, size/XL

#62 Add duplicate template test
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/resource.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#68 Fix webhook tests that create resources with irrelevant metadata
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
