Repository kubevirt/ssp-operator, pull requests merged in 2020-09, with the labels that each got.

#11 Added WIP message in readme
  README.md
Labels: dco-signoff: yes, size/XS

#12 Add reviewers and approvers
  OWNERS
Labels: dco-signoff: yes, size/S

#14 Added github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6 Add a TestSuite and other utils
  Makefile
  hack/build-functests.sh
  hack/build-in-container.sh
  hack/common.sh
  hack/config.sh
  hack/in-container.sh
  hack/run-functest.sh
  tests/TESTS.MD
  tests/build/Dockerfile
  tests/build/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, size/L
