Repository kubevirt/ssp-operator, pull requests merged in 2021-07, with the labels that each got.

#193 switch base image from golang-1.15 to ubi8/ubi-minimal
  Dockerfile
  validator.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#194 Fix VERSION variable in Makefile, fix Dockerfile, update CSV
  Dockerfile
  Makefile
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#196 Correct resources indentation for manager
  config/manager/manager.template.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#192 refactor reconcileOlderTemplates function
  internal/operands/common-templates/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#198 Stabilize functional tests
  tests/commonTemplates_test.go
  tests/labels_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#200 Update common-templates to v0.15.0
  data/common-templates-bundle/common-templates-v0.15.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.0.yaml
  internal/operands/common-templates/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#201 Remove a TODO comment from Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#204 Move test scripts from OCP CI jobs to automation directory
  automation/e2e-functests/run.sh
  automation/e2e-functests/setup.sh
  automation/e2e-upgrade-from-old-operator-functests/run.sh
  automation/e2e-upgrade-from-old-operator-functests/setup.sh
  automation/e2e-upgrade-functests/run.sh
  automation/e2e-upgrade-functests/setup.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#206 [release-v0.1] Move test scripts from OCP CI jobs to automation directory
  automation/e2e-functests/run.sh
  automation/e2e-functests/setup.sh
  automation/e2e-upgrade-from-old-operator-functests/run.sh
  automation/e2e-upgrade-from-old-operator-functests/setup.sh
  validator.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#205 [release-v0.11] Move test scripts from OCP CI jobs to automation directory
  automation/e2e-functests/run.sh
  automation/e2e-functests/setup.sh
  automation/e2e-upgrade-from-old-operator-functests/run.sh
  automation/e2e-upgrade-from-old-operator-functests/setup.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
