Repository kubevirt/ssp-operator, pull requests merged in 2021-01, with the labels that each got.

#72 Replace owner references with owner annotations for previously deployed templates during an upgrade
  controllers/ssp_controller.go
  internal/common/resource.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  tests/commonTemplates_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#75 Update common-template bundle to v0.13.0
  data/common-templates-bundle/common-templates-v0.13.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0.yaml
  internal/operands/common-templates/resource.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#76 Remove owner references for older templates with and Update api call instead of a Patch
  internal/common/resource.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#45 Add paused annotation
  api/v1beta1/ssp_types.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  controllers/ssp_controller.go
  data/crd/ssp.kubevirt.io_ssps.yaml
  tests/commonTemplates_test.go
  tests/metrics_test.go
  tests/nodeLabeller_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#71 Remove workload, flavor, os labels from templates which have older version
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#78 Fix templates test and other various fixes
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/common-templates/reconcile.go
  main.go
  tests/commonTemplates_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#79 Add support for environment vars to modify test timeouts
  tests/commonTemplates_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#74 [Bugfix] Make kubevirt-os-images visible to regular users
  internal/operands/common-templates/resource.go
  tests/commonTemplates_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#81 Fix csv-generator test image tag
  tests/e2e-test-csv-generator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#80 [Bugfix] Remove obsolete CPU models from node labels
  go.mod
  go.sum
  internal/operands/node-labeller/resources.go
  tests/nodeLabeller_test.go
  vendor/kubevirt.io/cpu-nfd-plugin/LICENSE
  vendor/kubevirt.io/cpu-nfd-plugin/pkg/config/config.go
  vendor/kubevirt.io/cpu-nfd-plugin/pkg/file/file.go
  vendor/kubevirt.io/cpu-nfd-plugin/pkg/util/util.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#83 [Bugfix] Give regular users permissions to view os images DataVolumes
  internal/operands/common-templates/resource.go
  tests/commonTemplates_test.go
  tests/tests_common_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#85 Common templates release v0.13.1
  data/common-templates-bundle/common-templates-v0.13.1.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.1.yaml
  internal/operands/common-templates/resource.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#84 Make os images tests more aesthetic
  tests/commonTemplates_test.go
  tests/tests_common_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#73 Adding important log messages
  controllers/ssp_controller.go
  internal/common/resource.go
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#93 Use a rhel8 template during testing instead of centos6
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#89 Small code cleanup
  internal/operands/node-labeller/resources.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#91 Fix csv-generator test
  tests/e2e-test-csv-generator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#95 Drop replace directive for cpu-nfd-plugin and update some dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#96 Update readme
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#77 Add observedGeneration to the SSP status
  api/v1beta1/ssp_types.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  controllers/ssp_controller.go
  data/crd/ssp.kubevirt.io_ssps.yaml
  tests/misc_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#99 Build and attach the test binary to a release
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#102 Add a script for upgrade testing used by OCP CI
  automation/ocp-ci-run-e2e-upgrade-tests.sh
  automation/ssp-cr-template.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
