Repository kubevirt/ssp-operator, pull requests merged in 2021-12, with the labels that each got.

#264 Update common-templates to v0.17.0
  data/common-templates-bundle/common-templates-v0.17.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#265 backport common-templates v0.15.2
  data/common-templates-bundle/common-templates-v0.15.2.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.2.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#268 [v0.1] Update OWNERS file to reflect current contributors
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#267 [v0.11] Update OWNERS file to reflect current contributors
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#270 Add missing test_id for one of DataImportCron tests
  tests/dataSources_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, approved

#266 [v0.12] Update OWNERS file to reflect current contributors
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#258 Add common labels into alert definitions
  internal/operands/metrics/resources.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved, ok-to-test

#269 Add initial controller to watch missing CRDs
  config/rbac/role.yaml
  controllers/crd_controller.go
  controllers/finishable/finishable.go
  controllers/setup.go
  controllers/ssp_controller.go
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/common/scheme.go
  internal/operands/common-templates/reconcile.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  main.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#271 Improve SSPCommonTemplatesModificationReverted Alert
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/resources.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#272 Update common-templates to v0.18.0
  data/common-templates-bundle/common-templates-v0.18.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#277 Disable failing tests
  tests/dataSources_test.go
Labels: dco-signoff: yes, size/XS, release-note-none
