Repository kubevirt/ssp-operator, pull requests merged in 2021-03, with the labels that each got.

#124 Extract label strings and simplify API calls with label selector
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/common-templates/resource.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#126 Move common-templates version to separate file
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#127 add deprecated label to old templates
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#133 Update common-templates to v0.14.0-rc.2
  data/common-templates-bundle/common-templates-v0.14.0-rc.2.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.14.0-rc.2.yaml
  internal/operands/common-templates/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#132 Update webhook version to admissionregistration.k8s.io/v1
  api/v1beta1/ssp_webhook.go
  config/default/webhook_ocp_cainjection_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#135 backport common templates v0.13.2
  data/common-templates-bundle/common-templates-v0.13.2.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.2.yaml
  internal/operands/common-templates/resource.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#137 Remove unused hack files
  Makefile
  hack/build-functests.sh
  hack/build-in-container.sh
  hack/run-functest.sh
  tests/build/Dockerfile
  tests/build/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#138 Template validator webhook rule for v1 VMs
  internal/operands/template-validator/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#98 ssp operator deletes the node-labeller
  internal/operands/node-labeller/defaults.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/node-labeller/reconcile_test.go
  internal/operands/node-labeller/resources.go
  tests/nodeLabeller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
