Repository kubevirt/ssp-operator, pull requests merged in 2021-08, with the labels that each got.

#195 [v0.11] Fix VERSION variable in Makefile, and update CSV
  Makefile
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#209 explain DeepCopy in template-validator
  internal/template-validator/webhooks/uplink.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#210 [admission-webhook] Use namespace in which the SSP CR was created for the placement validation dry-run
  api/v1beta1/ssp_webhook.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#211 Remove old docs
  tests/TESTS.MD
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#212 Code change: Fix issue found by sonarcloud
  internal/template-validator/validation/specialized.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#182 Enabling monitoring and adding basic alerts
  config/manager/manager.template.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/operands/metrics/resources.go
  internal/operands/template-validator/resources.go
  internal/template-validator/validator/app.go
  main.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#215 Fix recording rule names and add links to runbooks
  internal/operands/metrics/resources.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#218 Update common-templates to v0.15.1
  data/common-templates-bundle/common-templates-v0.15.1.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#208 Protect old style templates from deletion
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/resources.go
  internal/template-validator/labels/labels.go
  internal/template-validator/validator/app.go
  internal/template-validator/virtinformers/informers.go
  internal/template-validator/virtinformers/vmcache.go
  internal/template-validator/virtinformers/vmcache_test.go
  internal/template-validator/webhooks/admission.go
  internal/template-validator/webhooks/admission_test.go
  internal/template-validator/webhooks/hook.go
  internal/template-validator/webhooks/uplink.go
  internal/template-validator/webhooks/utils.go
  tests/commonTemplates_test.go
  tests/validator_test.go
  validator.Dockerfile
  vendor/github.com/openshift/client-go/LICENSE
  vendor/github.com/openshift/client-go/template/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/typed/template/v1/brokertemplateinstance.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/typed/template/v1/doc.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/typed/template/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/typed/template/v1/template.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/typed/template/v1/template_client.go
  vendor/github.com/openshift/client-go/template/clientset/versioned/typed/template/v1/templateinstance.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#220 Change securityContext on operator, so that scc is 'restricted'
  config/manager/manager.template.yaml
  tests/misc_test.go
Labels: dco-signoff: yes, size/M, lgtm, approved

#222 Rollback Golang version back to 1.15
  go.mod
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#221 [release-v0.11] Add the missing Generate csv
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#223 Update common-templates to v0.16.0
  data/common-templates-bundle/common-templates-v0.16.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#214 Add total_rejected_vms matrics
  internal/template-validator/webhooks/hook.go
  tests/metrics_test_utils.go
  tests/validator_test.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#227 Update common-templates to v0.16.1
  data/common-templates-bundle/common-templates-v0.16.1.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#225 Recording rule and alert for SSPHighRateRejectedVms
  internal/operands/metrics/resources.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#231 [release-v0.12] Regenerate files by running 'make container-build'
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#230 Regenerate files by running 'make container-build'
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#232 Reduce cognitive complexity
  hack/csv-generator.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved
