Repository kubevirt/ssp-operator, pull requests merged in 2021-04, with the labels that each got.

#141 move deprecated label to annotations
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#139 (v0.1) Template validator webhook rule for v1 VMs
  internal/operands/template-validator/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#142 backport deprecated annotation
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#140 Add a dry-run to verify placement fields
  api/v1beta1/ssp_webhook.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#144 Remove the relatedImages field from the CRD
  hack/csv-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#147 Update API version in unused config file
  config/crd/patches/webhook_in_ssps.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#145 Add UID to VersionCache
  internal/common/cache.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#148 Update vendored dependencies
  go.mod
  go.sum
  vendor/kubevirt.io/cpu-nfd-plugin/LICENSE
  vendor/kubevirt.io/cpu-nfd-plugin/pkg/config/config.go
  vendor/kubevirt.io/cpu-nfd-plugin/pkg/file/file.go
  vendor/kubevirt.io/cpu-nfd-plugin/pkg/util/util.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#149 Remove code related to node labeller
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  hack/csv-generator.go
  hack/csv-generator_test.go
  internal/common/environment.go
  internal/operands/node-labeller/defaults.go
  internal/operands/node-labeller/resources.go
  tests/e2e-test-csv-generator.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#152 Update k8s.io dependencies to v0.20.6
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/apiserverinternal/v1alpha1/generated.pb.go
  vendor/k8s.io/api/apps/v1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta2/generated.pb.go
  vendor/k8s.io/api/authentication/v1/generated.pb.go
  vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
  vendor/k8s.io/api/authorization/v1/generated.pb.go
  vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta2/generated.pb.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1beta1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/certificates/v1/generated.pb.go
  vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
  vendor/k8s.io/api/coordination/v1/generated.pb.go
  vendor/k8s.io/api/coordination/v1beta1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/discovery/v1alpha1/generated.pb.go
  vendor/k8s.io/api/discovery/v1beta1/generated.pb.go
  vendor/k8s.io/api/events/v1/generated.pb.go
  vendor/k8s.io/api/events/v1beta1/generated.pb.go
  vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/generated.pb.go
  vendor/k8s.io/api/flowcontrol/v1beta1/generated.pb.go
  vendor/k8s.io/api/networking/v1/generated.pb.go
  vendor/k8s.io/api/networking/v1beta1/generated.pb.go
  vendor/k8s.io/api/node/v1/generated.pb.go
  vendor/k8s.io/api/node/v1alpha1/generated.pb.go
  vendor/k8s.io/api/node/v1beta1/generated.pb.go
  vendor/k8s.io/api/policy/v1beta1/generated.pb.go
  vendor/k8s.io/api/rbac/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
  vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
  vendor/k8s.io/api/storage/v1/generated.pb.go
  vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/generated.pb.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#151 Update template-validator to version v0.10.0
  internal/operands/template-validator/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#153 Update cnv:vmi_status_running:count labels
  internal/operands/metrics/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#155 Add missing test ids in misc_tests.go
  tests/misc_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#157 Add missing test ids to metrics_test.go
  tests/metrics_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#158 Add missing test ids to commonTemplates_test.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#156 Add misisng test ids to webhook_test.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#159 Fix readme for building with custom image
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#160 Add build process to validator Dockerfile
  Makefile
  internal/template-validator/Dockerfile
  validator.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
