Repository kubevirt/ssp-operator, pull requests merged in 2021-11, with the labels that each got.

#249 Add metrics tests
  tests/commonTemplates_test.go
  tests/metrics_test_utils.go
  tests/misc_test.go
  tests/tests_common_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#251 Increase golang version to 1.16
  Dockerfile
  go.mod
  validator.Dockerfile
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#252 Update OWNERS file to reflect current contributors
  OWNERS
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#253 change ACTIONS_TOKEN to secrets.GITHUB_TOKEN
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#254 Revert "change ACTIONS_TOKEN to secrets.GITHUB_TOKEN"
  .github/workflows/release.yaml
Labels: size/XS, do-not-merge/release-note-label-needed, lgtm, dco-signoff: no

#255 Regenerate CRD
  data/crd/ssp.kubevirt.io_ssps.yaml
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#256 Fix csv-generator's invalid YAML output
  hack/csv-generator.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#259 Fix Alerts firing, metrics missing bug
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/template-validator/resources.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
