Repository kubevirt/ssp-operator, pull requests merged in 2021-09, with the labels that each got.

#233 Update common-templates to v0.16.2
  data/common-templates-bundle/common-templates-v0.16.2.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.2.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#235 Add "name" labels to deployments and pods
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/template-validator/resources.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#228 implement dataimportcron api
  Makefile
  api/v1beta1/constants.go
  api/v1beta1/ssp_types.go
  api/v1beta1/ssp_webhook.go
  api/v1beta1/ssp_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  go.mod
  go.sum
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/common-templates/resource.go
  tests/commonTemplates_test.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/register.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#236 Code change: Add global scheme variable for the operator
  controllers/ssp_controller.go
  internal/common/scheme.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  main.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#226 Code change: Improve validator code
  internal/template-validator/validation/eval.go
  internal/template-validator/validation/eval_test.go
  internal/template-validator/validation/path/conv.go
  internal/template-validator/validation/path/path.go
  internal/template-validator/validation/path/path_suite_test.go
  internal/template-validator/validation/path/path_test.go
  internal/template-validator/validation/path/variants.go
  internal/template-validator/validation/path/variants_test.go
  internal/template-validator/validation/rules.go
  internal/template-validator/validation/rules_test.go
  internal/template-validator/validation/specialized.go
  internal/template-validator/validation/specialized_test.go
  internal/template-validator/validation/test-utils/utils.go
  internal/template-validator/webhooks/admission_test.go
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#240 Add total_restored_common_templates metrics
  controllers/ssp_controller.go
  internal/common/resource.go
  internal/common/resource_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  main.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#239 Enable changing of namespace during run of ssp operator
  api/v1beta1/ssp_webhook.go
  api/v1beta1/ssp_webhook_test.go
  tests/commonTemplates_test.go
  tests/webhook_test.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#238 Load common templates before creating the operand
  controllers/ssp_controller.go
  internal/operands/common-templates/common-templates-test.yaml
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.12.2.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.13.1.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.14.0-rc.2.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.14.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.15.1.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.1.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.2.yaml
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/common-templates/resource.go
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/node-labeller/reconcile_test.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  main.go
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#242 Update CDI dependency to v1.40.0
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  go.mod
  go.sum
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_transfer.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved
