Repository kubevirt/ssp-operator, pull requests merged in 2021-06, with the labels that each got.

#176 [v0.11] Update webhook version for template validator to v1
  internal/operands/template-validator/resources.go
  internal/template-validator/webhooks/hook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#179 csv-generator: Override environment variables only when needed
  hack/csv-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#180 Update the default template-validator image to the latest released one
  Dockerfile
  Makefile
  internal/operands/template-validator/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#185 fixed deprecated label which is set during upgrade to up-to-date template
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#183 Adding info on building the Template Validator
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
