Repository kubevirt/ssp-operator, pull requests merged in 2021-05, with the labels that each got.

#163 Update common-templates to v0.14.0
  data/common-templates-bundle/common-templates-v0.14.0.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.14.0.yaml
  internal/operands/common-templates/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#164 Add missing test ids
  tests/commonTemplates_test.go
  tests/metrics_test.go
  tests/nodeLabeller_test.go
  tests/validator_test.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#161 Changes to inject template-validator image to ssp-operator build
  .gitignore
  Makefile
  config/manager/manager.template.yaml
  internal/operands/template-validator/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#162 Add release automation for template-validator
  .github/workflows/release.yaml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#167 Nominate kwiesmueller to approvers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#150 Test template-validator certificate rotation
  go.sum
  internal/operands/template-validator/resources.go
  tests/port-forwarding.go
  tests/tests_suite_test.go
  tests/validator_test.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#168 Improve code: Use constants instead of string literals
  controllers/ssp_controller.go
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/resource.go
  internal/operands/node-labeller/resources.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  tests/commonTemplates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#171 Cleanup Pull Request and Issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#169 Add priorityClassName to ssp-operator pod
  config/manager/manager.template.yaml
  internal/operands/template-validator/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#172 Add Resource requests to pods
  config/manager/manager.template.yaml
  internal/operands/template-validator/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#173 Force versions of 2 dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#174 [v0.2] Force versions of 2 dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#175 [v0.2] Add Resource requests to pods
  config/manager/manager.template.yaml
  internal/operands/template-validator/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#166 Update webhook version for template validator to v1
  internal/operands/template-validator/resources.go
  internal/template-validator/webhooks/hook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
