Repository kubevirt/ssp-operator, pull requests merged in 2021-02, with the labels that each got.

#104 Add readiness probe to the operator pod
  config/manager/manager.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#106 Integrate flags required by QE to generate reports
  go.mod
  go.sum
  tests/tests_suite_test.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#107 [release-v0.1] Backport qe tools
  go.mod
  go.sum
  tests/tests_suite_test.go
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/README.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/ginkgo/internal/global/init.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_darwin.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_dragonfly.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_freebsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux_mips64le.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_netbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_openbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_solaris.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_unix.go
  vendor/github.com/onsi/ginkgo/internal/suite/suite.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#108 Temporarily add sleep to upgrade test
  automation/ocp-ci-run-e2e-upgrade-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#97 Generate the CSV using csv-generator
  .travis.yml
  Makefile
  hack/csv-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#38 Add RBAC tests for OS Images
  tests/commonTemplates_test.go
  tests/tests_common_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#92 Add app.kubernetes.io labels to resources provisioned by ssp-operator
  automation/ssp-cr-template.yaml
  controllers/ssp_controller.go
  go.mod
  internal/common/labels.go
  internal/common/labels_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/template-validator/reconcile.go
  tests/commonTemplates_test.go
  tests/labels_test.go
  tests/metrics_test.go
  tests/nodeLabeller_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#111 Update node-labeller to pull virt-launcher image from quay
  internal/operands/node-labeller/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#109 csv-generator: populate spec.relatedImages
  hack/csv-generator.go
  internal/operands/node-labeller/defaults.go
  internal/operands/node-labeller/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#123 Create a builder for reconcile methods
  internal/common/resource.go
  internal/common/resource_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/template-validator/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#122 Regenerate CSV with related images added
  .gitignore
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#121 Remove global variables from resource objects
  internal/operands/node-labeller/resources.go
  internal/operands/template-validator/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#112 Migrate TravisCI jobs to Github actions
  .github/workflows/pull-request.yaml
  .github/workflows/release.yaml
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#125 Add remark on kustomize version
  Makefile
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
