Repository kubevirt/ssp-operator, pull requests merged in 2022-06, with the labels that each got.

#377 fix retrieving of prometheus token in tests
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/M, release-note-none, approved

#357 Adding controller for ssp-operator-metrics service
  config/default/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/service.yaml
  config/rbac/role.yaml
  controllers/services_controller.go
  controllers/setup.go
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/common/resource.go
  tests/service_controller_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#381 Increase timeouts for tests 5990 and 5989
  tests/tests_suite_test.go
  tests/webhook_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#382 add eventually in AfterEach in validator webhook tests which tries to delete template
  tests/validator_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#387 Update common-templates to v0.23.3
  data/common-templates-bundle/common-templates-v0.23.3.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved
