Repository kubevirt/ssp-operator, pull requests merged in 2022-10, with the labels that each got.

#418 Fix tests waiting for DVs to succeed
  tests/dataSources_test.go
  tests/misc_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#417 Watch required CRDs, and restart operator if they are removed
  controllers/crd_controller.go
  controllers/finishable/finishable.go
  controllers/services_controller.go
  controllers/setup.go
  controllers/ssp_controller.go
  internal/common/crypto_policy.go
  internal/common/environment.go
  internal/common/request.go
  internal/common/scheme.go
  internal/crd-watch/crd-watch.go
  internal/crd-watch/crd-watch_test.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/operand.go
  main.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/unconventionallisttypecrd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#401 Add missing webhook test and improve tests
  tests/commonTemplates_test.go
  tests/dataSources_test.go
  tests/env/env.go
  tests/labels_test.go
  tests/misc_test.go
  tests/monitoring_test.go
  tests/service_controller_test.go
  tests/single_node_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  tests/webhook_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#419 Update common-templates to v0.24.0
  data/common-templates-bundle/common-templates-v0.24.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#421 [release-v0.16] Fix tests waiting for DVs to succeed
  tests/dataSources_test.go
  tests/misc_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#427 add dockerfile for ci builds
  ci-builder/Dockerfile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm

#429 update controller-gen and kustomize
  Makefile
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
Labels: dco-signoff: yes, size/L, release-note-none, lgtm

#432 add gettext package to ci builder dockerfile
  ci-builder/Dockerfile
Labels: dco-signoff: yes, release-note-none

#426 Update common-templates to v0.24.1
  data/common-templates-bundle/common-templates-v0.24.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, approved
