Repository kubevirt/ssp-operator, pull requests merged in 2022-11, with the labels that each got.

#431 Add 0xFelix to approvers
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#437 Allow running the SSP Operator on plain kubernetes
  config/rbac/role.yaml
  controllers/setup.go
  controllers/ssp_controller.go
  internal/common/environment.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#416 Deploying state and tests for TLSSecurityProfile
  controllers/ssp_controller.go
  go.mod
  go.sum
  internal/common/crypto_policy.go
  internal/template-validator/tlsinfo/tlsinfo.go
  main.go
  tests/crypto_policy_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  vendor/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#442 Regenerate files by running "make container-build"
  data/crd/ssp.kubevirt.io_ssps.yaml
  internal/operands/node-labeller/reconcile.go
  internal/template-validator/validation/eval.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#443 Add the missing RBAC permissions to clusterversions in the CSV
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#447 [release-v0.16] Manual backport of deploying state and tests for TLSSecurityProfile
  controllers/ssp_controller.go
  go.mod
  go.sum
  internal/common/crypto_policy.go
  internal/template-validator/tlsinfo/tlsinfo.go
  main.go
  tests/crypto_policy_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  vendor/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm

#448 crypto_policy_test.go: Do not hardcode SSP deployment NS
  tests/crypto_policy_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#449 crypto_policy_test.go: Add test_ids
  tests/crypto_policy_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#454 crypto_policy_test.go: Do not hardcode SSP webhook service name
  tests/crypto_policy_test.go
  tests/env/env.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#455 [release-v0.16] crypto_policy_test.go: Do not hardcode SSP webhook service name
  tests/crypto_policy_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#456 OWNERS: Remove borod108 from reviewers
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#457 crypto_policy_test.go: Get CA bundle dynamically
  tests/crypto_policy_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#441 Cleanup fixes for tests waiting for DVs to succeed
  tests/dataSources_test.go
  tests/misc_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#459 [release-v0.16] Fix major and minor versions of Kubevirt and CDI used in CI
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
