Repository kubevirt/ssp-operator, pull requests merged in 2022-07, with the labels that each got.

#394 [backport release-v0.13] Update common-templates bundle to v0.19.6
  data/common-templates-bundle/common-templates-v0.19.6.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#396 [backport release-v0.12] change a way ho golang is installed in dockerfile
  Dockerfile
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.5.yaml
  validator.Dockerfile
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#393 [backport release-v0.12] Update common-templates bundle to v0.16.6
  data/common-templates-bundle/common-templates-v0.16.6.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.6.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#385 Add sanity tests for SSP alerts
  tests/metrics_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved, ok-to-test
