Repository kubevirt/ssp-operator, pull requests merged in 2022-03, with the labels that each got.

#320 Remove setup.sh scripts from automation folder
  automation/e2e-functests/setup.sh
  automation/e2e-upgrade-functests/run.sh
  automation/e2e-upgrade-functests/setup.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#319 Add default podAntiAffinity to PodTemplateSpec
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  tests/validator_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#315 Fix 'make generate' and 'make manifests'
  Makefile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#324 Update common-templates to v0.20.0
  data/common-templates-bundle/common-templates-v0.20.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#325 Add missing test IDs
  tests/dataSources_test.go
  tests/misc_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#326 Remove `GoldenImagesNSname` constant from `api` submodule
  api/v1beta1/constants.go
  internal/constants.go
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
  tests/dataSources_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/constants.go
  webhooks/ssp_webhook.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#321 Update OWNERS file
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#286 Add ServiceMonitor and E2E tests for Prometheus
  automation/e2e-upgrade-functests/run.sh
  config/default/kustomization.yaml
  config/manager/manager.template.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/service.yaml
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/metrics/resources.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  tests/cleanup_test.go
  tests/commonTemplates_test.go
  tests/metrics_test.go
  tests/misc_test.go
  tests/monitoring_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  vendor/github.com/jpillora/backoff/LICENSE
  vendor/github.com/jpillora/backoff/README.md
  vendor/github.com/jpillora/backoff/backoff.go
  vendor/github.com/jpillora/backoff/go.mod
  vendor/github.com/mwitkow/go-conntrack/.gitignore
  vendor/github.com/mwitkow/go-conntrack/.travis.yml
  vendor/github.com/mwitkow/go-conntrack/LICENSE
  vendor/github.com/mwitkow/go-conntrack/README.md
  vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go
  vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go
  vendor/github.com/mwitkow/go-conntrack/listener_reporter.go
  vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/common/config/config.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/golang.org/x/net/internal/timeseries/timeseries.go
  vendor/golang.org/x/net/trace/events.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/net/trace/trace.go
  vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#329 `e2e-upgrade-functests` lane tests release from a specified branch
  automation/e2e-upgrade-functests/run.sh
  hack/validate-no-offensive-lang.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#331 Remove selected template labels on reconcile
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#330 [release-v0.13] `e2e-upgrade-functests` lane tests release from a specified branch
  automation/e2e-upgrade-functests/run.sh
  automation/ocp-ci-run-e2e-upgrade-tests.sh
  hack/validate-no-offensive-lang.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#328 Add new column
  api/v1beta1/ssp_types.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved, ok-to-test
