Repository kubevirt/ssp-operator, pull requests merged in 2022-05, with the labels that each got.

#349 update openshift.io/scc label test
  tests/misc_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#347 update golang to version 1.18
  go.mod
  go.sum
Labels: dco-signoff: yes, release-note, size/XL, lgtm, approved

#345 Update common-templates to v0.21.0
  data/common-templates-bundle/common-templates-v0.21.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#348 replaced wget with curl in dockerfile
  Dockerfile
  validator.Dockerfile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#350 Update common-templates to v0.22.0
  data/common-templates-bundle/common-templates-v0.22.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#351 Log the reason why reconciliation is triggered
  controllers/ssp_controller.go
  internal/controller/handler-hook/handler_hook.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#354 Update common-templates to v0.23.1
  data/common-templates-bundle/common-templates-v0.23.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#360 update rhel 9 container link
  tests/misc_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#363 Added test id for custom DataImportCron created in custom namespaces
  tests/dataSources_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved, needs-ok-to-test

#366 Update github actions to use golang 1.18
  .github/workflows/pull-request.yaml
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#361 Add predicates to only watch relevant resource changes
  controllers/ssp_controller.go
  internal/controller/predicates/predicates.go
  internal/controller/predicates/predicates_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  tests/cleanup_test.go
  tests/monitoring_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#372 [release-v0.13] Update common-templates bundle to version v0.19.5
  data/common-templates-bundle/common-templates-v0.19.5.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm

#371 [release-v0.12] backport of common-templates release v0.16.5
  data/common-templates-bundle/common-templates-v0.16.5.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm

#367 Update common-templates to v0.23.2
  data/common-templates-bundle/common-templates-v0.23.2.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm

#374 [release-v0.13] Add predicates to only watch relevant resource changes
  Dockerfile
  controllers/ssp_controller.go
  internal/controller/handler-hook/handler_hook.go
  internal/controller/predicates/predicates.go
  internal/controller/predicates/predicates_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  tests/cleanup_test.go
  validator.Dockerfile
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#365 Fix tests ID 5990 and ID 5989
  tests/webhook_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved
