Repository kubevirt/ssp-operator, pull requests merged in 2022-12, with the labels that each got.

#452 Introduce support for deployments via kubevirtci and kubevirt
  .gitignore
  Makefile
  config/kubevirtci/kustomization.yaml
  config/kubevirtci/manager-disable-webhooks.yaml
  controllers/setup.go
  docs/development.md
  hack/kubevirt.sh
  hack/kubevirtci.sh
  hack/sync.sh
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#453 Deploy common-instancetypes v0.0.1-rc
  config/rbac/role.yaml
  controllers/setup.go
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/common/scheme.go
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-instancetypes/reconcile_test.go
  vendor/kubevirt.io/api/instancetype/register.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/deepcopy_generated.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/doc.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/register.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/types.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/types_swagger_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#462 Follow ups for common-instancetypes deployment
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-instancetypes/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#425 Add e2e tests for total_restored_common_templates metric
  tests/metrics_test.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#464 common-instancetypes: Update to v0.0.2-rc
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#467 common-instancetypes: Ensure CRDs are present before Cleanup
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-instancetypes/reconcile_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#468 kubevirtci: Move to _cluster-up
  .gitignore
  Makefile
  hack/kubevirtci.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#469 common-instancetypes: Add watched cluster CRDs to cleanup func test
  internal/operands/common-instancetypes/reconcile.go
  tests/cleanup_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#461 [release-v0.15] Update common-templates bundle to version v0.23.5
  data/common-templates-bundle/common-templates-v0.23.5.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm
