Repository kubevirt/ssp-operator, pull requests merged in 2022-08, with the labels that each got.

#405 [release-v0.15] CI: Fix Kubevirt and CDI versions
  automation/common/deploy-kubevirt-and-cdi.sh
  automation/common/versions.sh
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#409 Update CDI version to v1.53.0
  api/go.mod
  api/go.sum
  api/vendor/github.com/openshift/api/LICENSE
  api/vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_imagecontentpolicy.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  api/vendor/github.com/openshift/api/config/v1/doc.go
  api/vendor/github.com/openshift/api/config/v1/register.go
  api/vendor/github.com/openshift/api/config/v1/stringsource.go
  api/vendor/github.com/openshift/api/config/v1/types.go
  api/vendor/github.com/openshift/api/config/v1/types_apiserver.go
  api/vendor/github.com/openshift/api/config/v1/types_authentication.go
  api/vendor/github.com/openshift/api/config/v1/types_build.go
  api/vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  api/vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  api/vendor/github.com/openshift/api/config/v1/types_console.go
  api/vendor/github.com/openshift/api/config/v1/types_dns.go
  api/vendor/github.com/openshift/api/config/v1/types_feature.go
  api/vendor/github.com/openshift/api/config/v1/types_image.go
  api/vendor/github.com/openshift/api/config/v1/types_image_content_policy.go
  api/vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  api/vendor/github.com/openshift/api/config/v1/types_ingress.go
  api/vendor/github.com/openshift/api/config/v1/types_network.go
  api/vendor/github.com/openshift/api/config/v1/types_oauth.go
  api/vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  api/vendor/github.com/openshift/api/config/v1/types_project.go
  api/vendor/github.com/openshift/api/config/v1/types_proxy.go
  api/vendor/github.com/openshift/api/config/v1/types_scheduling.go
  api/vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  api/vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  api/vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#402 tests: RHEL: wait for DataVolume import and increase timeout
  tests/misc_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#406 CI: Move versions to a separate file
  automation/common/deploy-kubevirt-and-cdi.sh
  automation/common/versions.sh
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#404 Use https on runbooks URLs
  internal/operands/metrics/resources.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#410 add debug lines to DataImportCron template tests
  tests/dataSources_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#408 Support cluster-wide crypto policy
  controllers/services_controller.go
  controllers/ssp_controller.go
  go.mod
  go.sum
  internal/common/crypto_policy.go
  internal/common/environment.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  internal/template-validator/tlsinfo/tlsinfo.go
  internal/template-validator/tlsinfo/tlsinfo_test.go
  internal/template-validator/validator/app.go
  main.go
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved
