Repository kubevirt/ssp-operator, pull requests merged in 2022-04, with the labels that each got.

#332 Add metrics types to SSP metrics description
  docs/metrics.md
  internal/operands/metrics/resources.go
  tools/metricsdocs/metricsdocs.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, ok-to-test

#338 Revert golang version back to 1.17
  go.mod
  go.sum
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#336 Change docker commands into podman
  .github/workflows/release.yaml
  Makefile
  hack/config.sh
  tests/e2e-test-csv-generator.sh
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved, ok-to-test

#339 update validator dockerfile to use golang 1.18
  Makefile
  validator.Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#340 [Backport release-v0.13]bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#342 [backport release-v0.13] Update common-templates bundle to version v0.19.4
  data/common-templates-bundle/common-templates-v0.19.4.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#344 replace CT v0.19.4 with correct file
  data/common-templates-bundle/common-templates-v0.19.4.yaml
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#346 [backport release-v0.13] replace SRC_PVC_NAME and SRC_PVC_NAMESPACE
  data/common-templates-bundle/common-templates-v0.19.4.yaml
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved
