Repository kubevirt/ssp-operator, pull requests merged in 2022-01, with the labels that each got.

#275 Update common-templates bundle to version v0.16.4
  data/common-templates-bundle/common-templates-v0.16.4.yaml
  internal/operands/common-templates/data/common-templates-bundle/common-templates-v0.16.4.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#279 Update CDI API to v1.42.1
  go.mod
  go.sum
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#283 Parse VM from Template using Unstructured
  internal/template-bundle/bundle.go
  internal/template-bundle/bundle_test.go
  internal/template-bundle/template-bundle-test.yaml
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#282 Update common-templates to v.0.19.0
  data/common-templates-bundle/common-templates-v0.19.0.yaml
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/common-templates/version.go
  internal/template-bundle/bundle_test.go
  internal/template-bundle/template-bundle-test.yaml
Labels: dco-signoff: yes, size/XXL, release-note, lgtm

#262 Limit TemplateValidator Replicas in SNO mode
  config/rbac/role.yaml
  controllers/setup.go
  controllers/ssp_controller.go
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/common/environment.go
  internal/common/request.go
  internal/common/scheme.go
  internal/operands/template-validator/reconcile.go
  tests/single_node_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_proxy.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_featuregate.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_project.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/stringsource.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_operatorhub.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#288 Use CamelCased reason values in SSP status Condition
  controllers/ssp_controller.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved, ok-to-test

#289 Delete immutable resources only if immutable part was changed
  internal/common/resource.go
  internal/common/resource_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/data-sources/reconcile.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#285 Re-enable DataImportCronTests
  tests/dataSources_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#290 Update common-templates to v0.19.1
  data/common-templates-bundle/common-templates-v0.19.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, approved

#291 README.md: Remove node labeller functionality
  README.md
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved, ok-to-test

#292 fix applying deprecated label
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#294 Do not create DataImportCron if DataSource points to an existing PVC
  api/v1beta1/ssp_types.go
  controllers/setup.go
  controllers/ssp_controller.go
  internal/common/request.go
  internal/common/resource.go
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
  internal/template-bundle/bundle.go
  internal/template-bundle/bundle_test.go
  internal/template-bundle/template-bundle-test.yaml
  internal/test-utils/test_utils.go
  tests/dataSources_test.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#295 Update common-templates to v0.19.2
  data/common-templates-bundle/common-templates-v0.19.2.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#287 Change default log level to be less verbose
  controllers/ssp_controller.go
  internal/common/resource.go
  internal/operands/common-templates/reconcile.go
  main.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#263 Add tool to generate metrics documentation
  Makefile
  docs/metrics.md
  internal/operands/metrics/resources.go
  tools/metricsdocs/metricsdocs.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#298 Update common-templates to v0.19.3
  data/common-templates-bundle/common-templates-v0.19.3.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#297 Fix DataSource reconciliation when DataImportCron template is removed
  internal/operands/data-sources/reconcile.go
  tests/dataSources_test.go
  tests/misc_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#301 Change operator version to v0.14.0
  Makefile
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
