Repository kubevirt/ssp-operator, pull requests merged in 2023-07, with the labels that each got.

#615 chore: rename tekton operands
  internal/operands/tekton-pipelines/reconcile.go
  internal/operands/tekton-pipelines/reconcile_test.go
  internal/operands/tekton-tasks/reconcile.go
  internal/operands/tekton-tasks/reconcile_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#617 git rm -rf
  README.md
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#616 Audit RBAC rules
  config/rbac/role.yaml
  controllers/setup.go
  controllers/ssp_controller.go
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/tekton-pipelines/reconcile.go
  internal/operands/tekton-tasks/reconcile.go
  internal/operands/template-validator/reconcile.go
  internal/operands/vm-console-proxy/reconcile.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#614 chore: update CSV description
  config/manifests/bases/ssp-operator.clusterserviceversion.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#610 feat: Remove master branch option
  automation/e2e-upgrade-functests/run.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#624 Add Podman to ci-builder
  ci-builder/Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#625 feat: Add OWNERS_ALIASES and edit OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#627 Revert "feat: Add OWNERS_ALIASES and edit OWNERS file"
  OWNERS
  OWNERS_ALIASES
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#628 fix: GH actions for bumping virtio version
  .github/workflows/update-virtio-version.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#631 Update common-instancetypes to v0.3.1
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#632 Fix metrics linter script
  hack/prom_metric_linter.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#633 feat: add deploy VM console proxy feature gate
  api/v1beta2/ssp_types.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/samples/ssp_v1beta2_ssp.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#629 feat: Add github action that will add reviewer
  .github/workflows/add-reviewer-monitoring.yaml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#635 chore: Update virtio image version to v1.0.0
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
  internal/common/environment.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved
