Repository kubevirt/ssp-operator, pull requests merged in 2023-03, with the labels that each got.

#509 test: add and cleanup vm-console-proxy operand
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/test-utils/test_utils.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#516 fix: Update Kubevirt CR used in CI
  automation/common/deploy-kubevirt-and-cdi.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#513 fix: Wait for SSP operator to be ready after TLS policy tests
  tests/crypto_policy_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#495 lint: Introduce Makefile target, introduce pre-commit config and fix issues
  .golangci.yaml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  controllers/ssp_controller.go
  go.mod
  hack/csv-generator.go
  hack/csv-generator_test.go
  internal/common/environment.go
  internal/common/resource_test.go
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/data-sources/reconcile_test.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/node-labeller/reconcile_test.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/template-bundle/bundle.go
  internal/template-validator/service/service.go
  internal/template-validator/tlsinfo/tlsinfo.go
  internal/template-validator/tlsinfo/tlsinfo_test.go
  internal/template-validator/validation/eval.go
  internal/template-validator/validation/eval_test.go
  internal/template-validator/validation/path/path_test.go
  internal/template-validator/validation/rules_test.go
  internal/template-validator/validation/specialized_test.go
  internal/template-validator/virtinformers/vmcache.go
  internal/template-validator/virtinformers/vmcache_test.go
  internal/template-validator/webhooks/admission_test.go
  internal/template-validator/webhooks/utils.go
  tests/commonTemplates_test.go
  tests/crypto_policy_test.go
  tests/metrics_test_utils.go
  tests/watcher.go
  tools/metricsdocs/metricsdocs.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#522 chore: Use released Kubevirt CR in CI
  automation/common/deploy-kubevirt-and-cdi.sh
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#525 chore: Add lyarwood as approver to OWNERS
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#529 docs: Add golangci-lint and pre-commit dev docs
  docs/development.md
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#526 refactor + fix: Cleanup proxy bundle
  controllers/setup.go
  go.mod
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/vm-console-proxy-bundle/bundle-test-duplicate.yaml
  internal/vm-console-proxy-bundle/bundle-test-incorrect.yaml
  internal/vm-console-proxy-bundle/bundle-test.yaml
  internal/vm-console-proxy-bundle/bundle.go
  internal/vm-console-proxy-bundle/bundle_test.go
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#527 fix: console proxy and tests: Stabilize functional tests
  internal/operands/vm-console-proxy/reconcile.go
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#531 Use ImagePullPolicy: IfNotPresent instead of Always
  internal/operands/template-validator/resources.go
  internal/operands/vm-console-proxy/reconcile_test.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved
