Repository kubevirt/ssp-operator, pull requests merged in 2023-04, with the labels that each got.

#535 fix: stabilize functests of VM Console proxy
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#537 Added test_id for vnc_console_proxy
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#540 [release-v0.16] Cleanup fixes for tests waiting for DVs to succeed
  tests/dataSources_test.go
  tests/misc_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#538 fix: correctly delete proxy resources if namespace is not "kubevirt"
  internal/common/labels.go
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/test-utils/test_utils.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#524 Use `RUNBOOK_URL_TEMPLATE` env for the runbooks URL template
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/metrics/resources.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved, ok-to-test
