Repository kubevirt/ssp-operator, pull requests merged in 2023-01, with the labels that each got.

#470 common-instancetypes: Add missing README and dev docs
  README.md
  docs/development.md
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#474 Add `operator_health_impact` label to SSP alerts
  internal/operands/metrics/resources.go
  tests/metrics_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved, ok-to-test

#477 kubevirtci: Correct directory name
  hack/kubevirtci.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#479 metrics_test.go: Do not consider old ReplicaSets
  tests/metrics_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#481 Update common-instancetypes to v0.0.3-rc
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
Labels: dco-signoff: yes, release-note, size/XL, lgtm, approved

#476 data_sources: Always run the operand
  controllers/setup.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#483 feat: update ssp and validator ubi containers to rhel9 in dockerfile
  Dockerfile
  validator.Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#484 feat: bump golang version in ssp and validator containers
  Dockerfile
  validator.Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#487 Update common-instancetypes to v0.0.3
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved
