Repository kubevirt/ssp-operator, pull requests merged in 2023-12, with the labels that each got.

#744 feat: introduce dependabot config
  .github/dependabot.yml
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#777 chore: Update golang in CI to 1.20
  .github/workflows/pull-request.yaml
  .github/workflows/release.yaml
  ci-builder/Dockerfile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#747 fix: webhook: Don't check common template namespace
  tests/webhook_test.go
  webhooks/ssp_webhook.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#698 [release-v0.18] Apply metrics name linter
  Makefile
  go.mod
  go.sum
  hack/prom_metric_linter.sh
  tools/prom-metrics-collector/metrics_collector.go
  tools/prom-metrics-collector/metrics_json_generator.go
  vendor/github.com/kubevirt/monitoring/pkg/metrics/parser/metrics_parser.go
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#782 Update cnv:vmi_status_running:count
  internal/operands/metrics/resources.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#789 chore: Update golangci-lint to v1.55.2
  Makefile
  internal/operands/common-instancetypes/reconcile_test.go
  tests/dataSources_test.go
  tests/tekton-pipelines_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#788 fix: Use Route Status to get Prometheus host
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#792 fix: Fix querying for the latest release of ssp-operator
  automation/e2e-upgrade-functests/run.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#796 Update common-templates to v0.27.0
  data/common-templates-bundle/common-templates-v0.27.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved
