Repository kubevirt/ssp-operator, pull requests merged in 2023-11, with the labels that each got.

#720 chore: Regenerate CRD in data folder
  data/crd/ssp.kubevirt.io_ssps.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#728 fix: Incorrect DataSource reconciliation
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#721 [release-v0.16] Fix total_restored_common_templates metric update
  internal/common/resource.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm

#729 [release-v0.17] chore: Update version of vm-console-proxy container.
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/reconcile.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#732 feat: add evictionStrategy to VMs in tekton pipelines
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-customize-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#731 reconcile: Restore test that go deleted by accident
  internal/operands/data-sources/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#737 [release-v0.18] fix: Keep Ginkgo version in Makefile and go.mod in sync
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#735 reconcile_test: Extend DataSource / DataImportCron restore test
  internal/operands/data-sources/reconcile_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#740 [release-v0.16]feat: add .snyk file
  .snyk
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm

#738 [release-v0.18]feat: add .snyk file
  .snyk
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#739 [release-v0.17]feat: add .snyk file
  .snyk
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#741 adding polarion Id for VirtualMachineCRCErrors test
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved, ok-to-test

#743 chore: Regenerate CRD
  data/crd/ssp.kubevirt.io_ssps.yaml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#730 chore: Update virtio image version to v1.1.0
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
  internal/common/environment.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved
