Repository kubevirt/ssp-operator, pull requests merged in 2023-10, with the labels that each got.

#693 common-instancetypes: Wait until SSP is deployed during URI test
  tests/common_instancetypes_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#697 Update common-instancetypes to v0.3.4
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#696 fix: remove "cdi.kubevirt.io/storage.bind.immediate.requested" annotation from pipelines
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-customize-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#684 rbac: Audit `*` verbs of kubevirt-tekton-tasks
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/tekton-tasks/reconcile.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#706 feat: add snyk file to exclude vendor folders
  .snyk
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#661 common-instancetypes: Ignore attempts to reconcile virt-operator owned objects from bundle
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-instancetypes/reconcile_test.go
  tests/common_instancetypes_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#713 [release-v0.13] Fix CI by using a fixed KubeVirt version
  automation/common/deploy-kubevirt-and-cdi.sh
  automation/common/versions.sh
  automation/e2e-functests/run.sh
  automation/e2e-functests/setup.sh
  automation/e2e-upgrade-functests/run.sh
  automation/e2e-upgrade-functests/setup.sh
  automation/e2e-upgrade-functests/ssp-cr-template.yaml
  hack/validate-no-offensive-lang.sh
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#715 fix: instance types tests by waiting for ssp to be deployed
  tests/common_instancetypes_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#707 chore: Update virtio image version to v1.0.1
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
  internal/common/environment.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved
