Repository kubevirt/ssp-operator, pull requests merged in 2023-06, with the labels that each got.

#563 chore: remove old common-template manifests
  data/common-templates-bundle/common-templates-v0.12.2.yaml
  data/common-templates-bundle/common-templates-v0.13.0-rc.0.yaml
  data/common-templates-bundle/common-templates-v0.13.0.yaml
  data/common-templates-bundle/common-templates-v0.13.1.yaml
  data/common-templates-bundle/common-templates-v0.14.0-rc.2.yaml
  data/common-templates-bundle/common-templates-v0.14.0.yaml
  data/common-templates-bundle/common-templates-v0.15.0.yaml
  data/common-templates-bundle/common-templates-v0.15.1.yaml
  data/common-templates-bundle/common-templates-v0.16.0.yaml
  data/common-templates-bundle/common-templates-v0.16.1.yaml
  data/common-templates-bundle/common-templates-v0.16.2.yaml
  data/common-templates-bundle/common-templates-v0.17.0.yaml
  data/common-templates-bundle/common-templates-v0.18.0.yaml
  data/common-templates-bundle/common-templates-v0.19.0.yaml
  data/common-templates-bundle/common-templates-v0.19.1.yaml
  data/common-templates-bundle/common-templates-v0.19.2.yaml
  data/common-templates-bundle/common-templates-v0.19.3.yaml
  data/common-templates-bundle/common-templates-v0.20.0.yaml
  data/common-templates-bundle/common-templates-v0.21.0.yaml
  data/common-templates-bundle/common-templates-v0.22.0.yaml
  data/common-templates-bundle/common-templates-v0.23.0.yaml
  data/common-templates-bundle/common-templates-v0.23.1.yaml
  data/common-templates-bundle/common-templates-v0.23.2.yaml
  data/common-templates-bundle/common-templates-v0.23.3.yaml
  data/common-templates-bundle/common-templates-v0.23.4.yaml
  data/common-templates-bundle/common-templates-v0.24.0.yaml
  data/common-templates-bundle/common-templates-v0.24.1.yaml
  data/common-templates-bundle/common-templates-v0.24.2.yaml
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#561 fix(CNV-29287): do not watch tekton crd
  internal/operands/tekton-pipelines/tekton-pipelines.go
  internal/operands/tekton-tasks/tekton-tasks.go
  tests/tekton-pipelines_test.go
  tests/tekton-tasks_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#566 fix: add virtualMachine.kubevirt.io crd to required crds
  README.md
  controllers/setup.go
  controllers/vm_controller.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#567 fix(CNV-29761): ensure that tekton crd exists
  internal/common/labels.go
  internal/operands/tekton-pipelines/tekton-pipelines.go
  internal/operands/tekton-tasks/tekton-tasks.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#565 feat: Add checking that all files are committed
  .github/workflows/pull-request.yaml
  hack/check-commited-changes.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#559 Fix total_restored_common_templates metric update
  internal/common/resource.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  main.go
  tests/metrics_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#574 chore: Fix check_commited_files
  go.mod
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#550 feat: rework example pipelines
  automation/e2e-tekton/example-pipelines-test.sh
  automation/e2e-tekton/test-files/configmap.yaml
  automation/e2e-tekton/test-files/http-server.yaml
  automation/e2e-tekton/test-files/windows10-customize-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows10-dv.yaml
  automation/e2e-tekton/test-files/windows10-installer-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows11-customize-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows11-dv.yaml
  automation/e2e-tekton/test-files/windows11-installer-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows2k22-customize-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows2k22-dv.yaml
  automation/e2e-tekton/test-files/windows2k22-installer-pipelinerun.yaml
  controllers/setup.go
  data/tekton-pipelines/kubernetes/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/kubernetes/windows-customize-pipeline.yaml
  data/tekton-pipelines/kubernetes/windows-efi-installer-pipeline.yaml
  data/tekton-pipelines/okd/windows-bios-installer-configmaps.yaml
  data/tekton-pipelines/okd/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/okd/windows-customize-configmaps.yaml
  data/tekton-pipelines/okd/windows-customize-pipeline.yaml
  data/tekton-pipelines/okd/windows-efi-installer-configmaps.yaml
  data/tekton-pipelines/okd/windows-efi-installer-pipeline.yaml
  data/tekton-pipelines/pipelines-rbac.yaml
  data/tekton-pipelines/windows-bios-installer-configmaps.yaml
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-customize-configmaps.yaml
  data/tekton-pipelines/windows-customize-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-configmaps.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
  internal/operands/tekton-pipelines/tekton-pipelines.go
  internal/tekton-bundle/tekton-bundle.go
  internal/tekton-bundle/tekton-bundle_test.go
  tests/tekton-pipelines_test.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#573 Update common-instancetypes to v0.2.0
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#580 [release-v0.17] chore: Fix kubevirt and CDI versions in CI
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#577 chore: add vm-console-proxy annotations
  config/samples/ssp_v1beta2_ssp.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#576 docs: improve SSP documentation
  README.md
  docs/configuration.md
  docs/development.md
  docs/installation.md
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#581 fix: Keep API v1beta1 in scheme.
  PROJECT
  automation/e2e-upgrade-functests/ssp-cr-template.yaml
  internal/common/scheme.go
  tests/tests_suite_test.go
  tests/webhook_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/groupversion_info.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
  webhooks/ssp_webhook.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/XL, release-note-none, approved

#584 Update common-instancetypes to v0.3.0
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#591 [release-v0.18] Fix env variables
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#592 fix(CNV-30284): rename tekton images env vars
  internal/common/environment.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#569 feat: Change ssp master to main
  .github/workflows/validate-no-offensive-lang.yml
  README.md
  automation/e2e-upgrade-functests/run.sh
  tests/TESTS.MD
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#595 Don't override autoupdated datasources that point to a snapshot instead of PVC
  Makefile
  hack/kubevirtci.sh
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#611 fix: fix default instanceTypeName parameter in tekton pipelines
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-customize-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved
