Repository kubevirt/ssp-operator, pull requests merged in 2023-08, with the labels that each got.

#650 fix: Remove add user workflow
  .github/workflows/add-reviewer-monitoring.yaml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#643 Change metrics names
  controllers/ssp_controller.go
  docs/metrics.md
  internal/common/resource.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/metrics/resources.go
  internal/template-validator/webhooks/hook.go
  main.go
  tests/metrics_test.go
  tests/metrics_test_utils.go
  tests/misc_test.go
  tests/monitoring_test.go
  tests/tests_common_test.go
  tests/validator_test.go
  tools/metricsdocs/metricsdocs.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#651 feat: Rework add reviewer workflow
  .github/workflows/add-reviewer-monitoring.yaml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#608 fix(CNV-28185): add required labels
  controllers/services_controller.go
  tests/service_controller_test.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#654 Force runbooks names to equal alerts names
  tests/metrics_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#649 chore: Move to kubevirt v1.0.0
  go.mod
  go.sum
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#656 [release-v0.18] Change metrics names
  controllers/ssp_controller.go
  docs/metrics.md
  internal/common/resource.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/metrics/resources.go
  internal/template-validator/webhooks/hook.go
  main.go
  tests/metrics_test.go
  tests/metrics_test_utils.go
  tests/misc_test.go
  tests/monitoring_test.go
  tests/tests_common_test.go
  tests/validator_test.go
  tools/metricsdocs/metricsdocs.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#655 fix: CI uses the latest released Kubevirt
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#642 Update common-instancetypes to v0.3.2
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#640 fix: CrashLoopBackOff once tlsProfile changed
  controllers/ssp_controller.go
  internal/common/crypto_policy.go
  internal/template-validator/tlsinfo/tlsinfo.go
  main.go
  tests/crypto_policy_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#645 fix: Use the latest image of vm-console-proxy
  .github/workflows/release-vm-console-proxy.yaml
  config/manager/manager.template.yaml
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  hack/csv-generator.go
  hack/csv-generator_test.go
  internal/common/environment.go
  internal/operands/vm-console-proxy/defaults.go
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/vm-console-proxy-bundle/bundle-test-duplicate.yaml
  internal/vm-console-proxy-bundle/bundle-test-incorrect.yaml
  internal/vm-console-proxy-bundle/bundle-test.yaml
  internal/vm-console-proxy-bundle/bundle.go
  internal/vm-console-proxy-bundle/bundle_test.go
  tests/e2e-test-csv-generator.sh
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, release-note, size/XL, lgtm, approved

#646 feat: replace namespace of configMaps and roleBindings
  internal/operands/tekton-pipelines/reconcile.go
  internal/operands/tekton-pipelines/reconcile_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#648 fix: change delete object type in clean up section in efi pipeline
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
Labels: dco-signoff: yes, size/XS, release-note, lgtm

#670 [release-v0.18] fix: Use the latest image of vm-console-proxy
  .github/workflows/release-vm-console-proxy.yaml
  config/manager/manager.template.yaml
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  hack/csv-generator.go
  hack/csv-generator_test.go
  internal/common/environment.go
  internal/operands/vm-console-proxy/defaults.go
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/vm-console-proxy-bundle/bundle-test-duplicate.yaml
  internal/vm-console-proxy-bundle/bundle-test-incorrect.yaml
  internal/vm-console-proxy-bundle/bundle-test.yaml
  internal/vm-console-proxy-bundle/bundle.go
  internal/vm-console-proxy-bundle/bundle_test.go
  tests/e2e-test-csv-generator.sh
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, release-note, size/XL, lgtm, approved

#673 [release-v0.18] Add VirtualMachineCRCErrors alert
  Dockerfile
  Makefile
  config/rbac/role.yaml
  controllers/setup.go
  controllers/vm_controller.go
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  docs/development.md
  docs/metrics.md
  go.mod
  go.sum
  internal/common/scheme.go
  internal/operands/metrics/resources.go
  main.go
  pkg/monitoring/metrics/metrics.go
  pkg/monitoring/metrics/metrics_suite_test.go
  pkg/monitoring/metrics/rbd_metrics.go
  pkg/monitoring/metrics/rbd_metrics_test.go
  tests/monitoring_test.go
  tools/metricsdocs/metricsdocs.go
  vendor/github.com/machadovilaca/operator-observability/LICENSE
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/metric.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/consist_of.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/alertmanager_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/prometheus_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#674 Update common-templates to v0.26.0
  data/common-templates-bundle/common-templates-v0.26.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#676 fix: bump k8s dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#634 refactor(CNV-31248): remove namespace annotation
  automation/e2e-upgrade-functests/run.sh
  config/samples/ssp_v1beta2_ssp.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  docs/configuration.md
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/env/env.go
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved
