Repository kubevirt/ssp-operator, pull requests merged in 2023-09, with the labels that each got.

#678 [release-v0.18] refactor(CNV-31248): remove namespace annotation
  automation/e2e-upgrade-functests/run.sh
  config/samples/ssp_v1beta2_ssp.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/env/env.go
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#679 fix: fix wrong parsing of vm.spec.template.spec.domain.memory.guest in validator
  internal/template-validator/validation/path/path.go
  internal/template-validator/validation/path/path_test.go
  internal/template-validator/validation/test-utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#683 fix: replacing of namespace annotation when openshift-cnv namespace is set
  data/tekton-pipelines/pipelines-rbac.yaml
  data/tekton-pipelines/windows-bios-installer-configmaps.yaml
  data/tekton-pipelines/windows-customize-configmaps.yaml
  internal/operands/tekton-pipelines/reconcile.go
  internal/operands/tekton-pipelines/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#686 Reduce VirtualMachineCRCErrors noise
  internal/operands/metrics/resources.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#685 Do not register VM controller if KubeVirt CRDs are not installed
  controllers/setup.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#688 Update common-instancetypes to v0.3.3
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved
