Repository kubevirt/ssp-operator, pull requests merged in 2023-05, with the labels that each got.

#541 [release-v0.17] fix: correctly delete proxy resources if namespace is not "kubevirt"
  internal/common/labels.go
  internal/operands/vm-console-proxy/reconcile.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#542 refactor: Remove RequiredCrds() method from operands
  controllers/setup.go
  controllers/ssp_controller.go
  internal/common/request.go
  internal/crd-watch/crd-watch.go
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-instancetypes/reconcile_test.go
  internal/operands/common-templates/reconcile.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/operand.go
  internal/operands/template-validator/reconcile.go
  internal/operands/vm-console-proxy/reconcile.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#544 refactor: add default update and status functions
  internal/common/resource.go
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
  internal/operands/node-labeller/reconcile.go
  internal/operands/template-validator/reconcile.go
  internal/operands/vm-console-proxy/reconcile.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#551 fix: wait for ssp operator in pipelines tests
  automation/e2e-tekton/example-pipelines-test.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#552 feat: migrate automation for bumping virtio version
  .github/workflows/update-virtio-version.yaml
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#547 Update container list
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  data/tekton-tasks/kubevirt-tekton-tasks-kubernetes.yaml
  data/tekton-tasks/kubevirt-tekton-tasks-okd.yaml
  hack/csv-generator.go
  hack/csv-generator_test.go
  internal/common/environment.go
  internal/common/environment_test.go
  internal/operands/tekton-tasks/tekton-tasks.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#555 fix: add validator image variable to pipeline test scripts
  automation/e2e-tekton/example-pipelines-test.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm

#556 fix: correct tekton manifests path in release script
  .github/workflows/release-tekton-tasks.yaml
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  data/tekton-tasks/kubevirt-tekton-tasks-kubernetes.yaml
  data/tekton-tasks/kubevirt-tekton-tasks-okd.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd.yaml
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm

#557 fix: fix wrong version of tekton tasks containers
  .github/workflows/release-tekton-tasks.yaml
  internal/common/version.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#545 docs: Improve description
  README.md
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
