Repository kubevirt/ssp-operator, pull requests merged in 2023-02, with the labels that each got.

#489 ci: add release-vm-console-proxy workflow
  .github/workflows/release-vm-console-proxy.yaml
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#486 Add alert for rhel6 running vms
  controllers/reconciler.go
  controllers/services_controller.go
  controllers/setup.go
  controllers/vm_controller.go
  docs/development.md
  internal/common/scheme.go
  internal/operands/metrics/resources.go
  main.go
  tests/metrics_test.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#490 Move TemplateValidator and NodeLabeller to pointers
  api/v1beta1/ssp_types.go
  api/v1beta1/zz_generated.deepcopy.go
  internal/controller/predicates/predicates_test.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  tests/misc_test.go
  tests/monitoring_test.go
  tests/single_node_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  tests/webhook_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/zz_generated.deepcopy.go
  webhooks/ssp_webhook.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#496 Update common-templates to v0.25.0
  data/common-templates-bundle/common-templates-v0.25.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#497 Update common-instancetypes to v0.1.0
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#501 docs: add info about vm-console-proxy
  README.md
  docs/development.md
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#504 functest: Switch to calling ginkgo using go run
  Makefile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#498 test: add vm-console-proxy functional tests
  automation/e2e-upgrade-functests/run.sh
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/cleanup_test.go
  tests/env/env.go
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved
