Repository kubevirt/ssp-operator, pull requests merged in 2024-07, with the labels that each got.

#1002 fix: typo in deploy-kubevirt-and-cdi.sh
  automation/common/deploy-kubevirt-and-cdi.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved, ok-to-test

#1011 Fix runbook_url test
  tests/metrics_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1010 deps: Update ci-builder to go 1.22.5
  ci-builder/Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1015 ci-builder: Lower go version to downstream version
  ci-builder/Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1016 Update common-templates to v0.29.2
  data/common-templates-bundle/common-templates-v0.29.2.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1018 api: Add a config option for vm-console-proxy and deprecate the feature gate
  api/v1beta2/ssp_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#1024 fix: regenerate vendor files
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/zz_generated.deepcopy.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1023 CI: Use compatible tekton version v0.67
  automation/common/versions.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved
