Repository kubevirt/ssp-operator, pull requests merged in 2024-01, with the labels that each got.

#807 [release-v0.18] chore: update tekton-tasks manifests to v0.15.1
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd.yaml
  internal/common/version.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#818 Revert "[release-v0.18] Update common-templates to v0.27.0"
  data/common-templates-bundle/common-templates-v0.27.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#819 [release-v0.18] rbac: Audit `*` verbs from kubevirt-tekton-tasks
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/tekton-tasks/tekton-tasks.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#742 Fix VirtualMachineCRCErrors not stop firing
  controllers/vm_controller.go
  docs/metrics.md
  internal/operands/metrics/resources.go
  pkg/monitoring/metrics/rbd_metrics.go
  pkg/monitoring/metrics/rbd_metrics_test.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#817 chore: Update virtio image version to v1.1.1
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
  internal/common/environment.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm

#787 fix: add required labels to pods
  internal/common/labels.go
  internal/operands/template-validator/reconcile.go
  internal/operands/vm-console-proxy/reconcile.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#826 feat: dependabot configuration
  .github/dependabot.yml
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#835 feat: set special labels to dependabot PRs
  .github/dependabot.yml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#840 fix: increase partition1 size in windows efi configmaps
  data/tekton-pipelines/windows-efi-installer-configmaps.yaml
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#854 feat: update golang to 1.21
  .github/workflows/pull-request.yaml
  .github/workflows/release.yaml
  Dockerfile
  api/go.mod
  ci-builder/Dockerfile
  go.mod
  go.sum
  validator.Dockerfile
  vendor/modules.txt
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#847 chore(deps): Bump the production-dependencies group with 12 updates
  go.mod
  go.sum
  internal/common/resource_test.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/profiles_and_reports.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/outline/ginkgo.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/outline/import.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo_t_dsl.go
  vendor/github.com/onsi/ginkgo/v2/internal/spec_context.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/RELEASE.md
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/delegating_by_gvk_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/restmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/field/selector/utils.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/syncs/syncs.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#850 Update VM controller error handling
  controllers/vm_controller.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#848 feat: Metrics unit tests
  Makefile
  hack/metrics-rules-test.sh
  internal/operands/metrics/resources.go
  pkg/monitoring/rules/rules-tests.yaml
  pkg/monitoring/rules/rules.go
  tests/monitoring_test.go
  tools/metricsdocs/metricsdocs.go
  tools/prom-metrics-collector/metrics_collector.go
  tools/test-rules-writer/test_rules_writer.go
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#845 fix: set boot source labels for DVs created by windows pipelines
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#863 Remove 'codingben' from OWNERS
  OWNERS
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
