Repository kubevirt/ssp-operator, pull requests merged in 2024-02, with the labels that each got.

#868 [release-v0.18] fix: Use TokenRequest API to get prometheus token
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#874 chore: Remove workflow: add-reviewer-monitoring.yaml
  .github/workflows/add-reviewer-monitoring.yaml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#876 [release-v0.18] fix: Incorrect DataSource reconciliation
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#870 Refactor recording rules and alerts code
  docs/metrics.md
  internal/operands/metrics/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/metrics/resources.go
  internal/template-validator/validator/app.go
  main.go
  pkg/monitoring/metrics/ssp-operator/metrics.go
  pkg/monitoring/metrics/template-validator/metrics.go
  pkg/monitoring/rules/alerts/operator.go
  pkg/monitoring/rules/alerts/prometheus.go
  pkg/monitoring/rules/recordingrules/operator.go
  pkg/monitoring/rules/recordingrules/recordingrules.go
  pkg/monitoring/rules/rules-tests.yaml
  pkg/monitoring/rules/rules.go
  tests/metrics_test.go
  tests/monitoring_test.go
  tools/metricsdocs/metricsdocs.go
  tools/prom-metrics-collector/metrics_collector.go
  tools/prom-metrics-collector/metrics_json_generator.go
  tools/test-rules-writer/test_rules_writer.go
  vendor/github.com/machadovilaca/operator-observability/pkg/docs/alerts.go
  vendor/github.com/machadovilaca/operator-observability/pkg/docs/metrics.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/rbac.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/recordingrule.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/schema.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#885 feat: remove script for downloading tekton tasks manifests
  .github/workflows/release-tekton-tasks.yaml
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#886 [release-v0.19] Rename VirtualMachineCRCErrors to VMStorageClassWarning
  internal/operands/metrics/resources.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#879 fix: Remove namespaceSelector from webhook definition
  config/rbac/role.yaml
  controllers/controllers_suite_test.go
  controllers/reconciler.go
  controllers/setup.go
  controllers/webhook_controller.go
  controllers/wehook_test.go
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  tests/webhook_controller_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#890 test: Disable flaky test: [test_id:10549] Should fire VMStorageClassWarning when rxbounce is disabled
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#895 fix: Remove use of kubevirt.io/v1alpha3 in template-validator tests
  internal/template-validator/validation/test-utils/utils.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#898 chore: Update Ginkgo version in Makefile
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#902 [release-v0.18] chore: Update of common-instancetypes bundles to v0.3.5
  data/common-instancetypes-bundle/common-clusterinstancetypes-bundle.yaml
  data/common-instancetypes-bundle/common-clusterpreferences-bundle.yaml
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved
