Repository kubevirt/ssp-operator, pull requests merged in 2024-08, with the labels that each got.

#1025 [release-v0.20] CI: Fix Kubevirt, CDI and Tekton versions
  automation/common/versions.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1027 [release-v0.18] CI: Use compatible tekton version v0.67
  automation/common/versions.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1026 [release-v0.19] CI: Use compatible tekton version v0.67
  automation/common/versions.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1029 Update common-templates to v0.29.3
  data/common-templates-bundle/common-templates-v0.29.3.yaml
  internal/operands/common-templates/version.go
  renovate.json
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1033 fix: common-instancetypes: Clear URL when deploying from bundle
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-instancetypes/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1045 chore: enable gomodTidy in renovate
  renovate.json
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1046 Update vm-console-proxy
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/defaults.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1051 Revert "api: Add config option for vm-console-proxy, deprecate feature gate"
  api/v1beta2/ssp_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/tests_suite_test.go
  tests/vm_console_proxy_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/zz_generated.deepcopy.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved
