Repository kubevirt/ssp-operator, pull requests merged in 2024-12, with the labels that each got.

#1150 feat: architecture dependent template reading
  internal/template-bundle/bundle.go
  internal/template-bundle/bundle_test.go
  internal/template-bundle/template-bundle-test.yaml
  tests/commonTemplates_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#1155 [release-v0.19] makefile: fix: Update controller-gen version to v0.14.0
  .github/workflows/pull-request.yaml
  Makefile
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  vendor/kubevirt.io/ssp-operator/api/v1beta1/zz_generated.deepcopy.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/zz_generated.deepcopy.go
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#1159 chore(observability): Bump operator observability version 0.0.24
  go.mod
  go.sum
  pkg/monitoring/rules/alerts/prometheus.go
  pkg/monitoring/rules/recordingrules/recordingrules.go
  pkg/monitoring/rules/rules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector_result.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/metric.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/compatibility.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1156 feat: read architecture specific common templates file
  internal/controllers/setup.go
  internal/template-bundle/bundle.go
  internal/template-bundle/bundle_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1166 makefile: Fix podman manifest push command
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1168 Update common-templates to v0.32.2
  data/common-templates-bundle/common-templates-amd64-v0.32.2.yaml
  data/common-templates-bundle/common-templates-s390x-v0.32.2.yaml
  data/common-templates-bundle/common-templates-v0.32.2.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1153 Update common-templates bundle to version v0.27.1
  data/common-templates-bundle/common-templates-v0.27.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1176 chore(golangci-lint): Bump golangci-lint 1.62.2
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1184 chore(deps): update module golang.org/x/net to v0.33.0
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/LICENSE
  api/vendor/golang.org/x/net/http2/client_conn_pool.go
  api/vendor/golang.org/x/net/http2/config.go
  api/vendor/golang.org/x/net/http2/config_go124.go
  api/vendor/golang.org/x/net/http2/config_pre_go124.go
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/http2.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/testsync.go
  api/vendor/golang.org/x/net/http2/timer.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/net/http2/unencrypted.go
  api/vendor/golang.org/x/net/http2/write.go
  api/vendor/golang.org/x/net/http2/writesched_priority.go
  api/vendor/golang.org/x/text/LICENSE
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#1185 [release-v0.22] chore(deps): update module golang.org/x/net to v0.33.0
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/LICENSE
  api/vendor/golang.org/x/net/http2/client_conn_pool.go
  api/vendor/golang.org/x/net/http2/config.go
  api/vendor/golang.org/x/net/http2/config_go124.go
  api/vendor/golang.org/x/net/http2/config_pre_go124.go
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/http2.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/testsync.go
  api/vendor/golang.org/x/net/http2/timer.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/net/http2/unencrypted.go
  api/vendor/golang.org/x/net/http2/write.go
  api/vendor/golang.org/x/net/http2/writesched_priority.go
  api/vendor/golang.org/x/text/LICENSE
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved
