Repository kubevirt/ssp-operator, pull requests merged in 2024-06, with the labels that each got.

#989 Update common-templates to v0.29.0
  data/common-templates-bundle/common-templates-v0.29.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#984 Alert VMStorageClassWarning only for Windows VMs
  pkg/monitoring/rules/alerts/operator.go
  pkg/monitoring/rules/rules-tests.yaml
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#997 chore: Move downstream edited constants to a single file.
  internal/constants.go
  internal/env/env.go
  internal/env/env_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#998 Update common-templates to v0.29.1
  data/common-templates-bundle/common-templates-v0.29.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1000 fix: enable make unittest for different architectures.
  Makefile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, ok-to-test
