Repository kubevirt/ssp-operator, pull requests merged in 2024-09, with the labels that each got.

#1068 feat: multiarch compatibility to validator.Dockerfile
  validator.Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved, ok-to-test

#1076 tests: On cleanup, wait until PVCs are bound.
  tests/dataSources_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1082 Update common-templates to v0.31.0
  data/common-templates-bundle/common-templates-v0.31.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1083 Revert "tests: On cleanup, wait until PVCs are bound."
  tests/dataSources_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1087 feat: Remove unused git from Dockerfile
  Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1089 [release-v0.21] Update common-templates bundle to version v0.31.1
  data/common-templates-bundle/common-templates-v0.31.1.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved
