Repository kubevirt/ssp-operator, pull requests merged in 2024-03, with the labels that each got.

#900 chore: Add script to sync common-instancetypes
  hack/bump-common-instancetypes.sh
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#907 [release-v0.18] Fix VirtualMachineCRCErrors not stop firing
  controllers/vm_controller.go
  docs/metrics.md
  internal/operands/metrics/resources.go
  pkg/monitoring/metrics/rbd_metrics.go
  pkg/monitoring/metrics/rbd_metrics_test.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#913 Adjust VMStorageClassWarning E2E MatchError timeout
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#921 [release-v0.18] chore: bump google.golang.org/protobuf package to 1.33
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#922 [release-v0.17] chore: update google.golang.org/protobuf package to 1.33
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#923 [releasev0.16] chore: update google.golang.org/protobuf package to 1.33
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm

#916 chore: Update vm-console-proxy to v0.5.0
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/defaults.go
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/vm-console-proxy-bundle/bundle-test.yaml
  internal/vm-console-proxy-bundle/bundle.go
  internal/vm-console-proxy-bundle/bundle_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#925 Replace test 'Eventually-Consistently' with 'Eventually-MustPassRepeatedly
  tests/monitoring_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#919 chore: Update virtio image version to v1.2.0
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
  internal/common/environment.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#932 Apply monitoring linters
  Makefile
  go.mod
  go.sum
  pkg/monitoring/rules/rules.go
  pkg/monitoring/rules/rules_test.go
  vendor/github.com/grafana/regexp/.gitignore
  vendor/github.com/grafana/regexp/LICENSE
  vendor/github.com/grafana/regexp/README.md
  vendor/github.com/grafana/regexp/backtrack.go
  vendor/github.com/grafana/regexp/exec.go
  vendor/github.com/grafana/regexp/onepass.go
  vendor/github.com/grafana/regexp/regexp.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#939 automation: Remove update-virtio-version github action
  .github/workflows/update-virtio-version.yaml
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved
