Repository kubevirt/ssp-operator, pull requests merged in 2024-10, with the labels that each got.

#1099 Rename VirtualMachineCRCErrors to VMStorageClassWarning
  internal/operands/metrics/resources.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#1091 s390x enablement. Update Makefile and Dockerfiles
  Dockerfile
  Makefile
  validator.Dockerfile
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved, ok-to-test

#1108 refactor: suggestions from sonarcloud quality gate
  Dockerfile
  validator.Dockerfile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, ok-to-test
