Repository kubevirt/ssp-operator, pull requests merged in 2024-11, with the labels that each got.

#1122 Fix flaky test fire VMStorageClassWarning when rxbounce is disabled
  tests/monitoring_test.go
  tests/tests_common_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1128 makefile: use the same ginkgo version that is in go.mod
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1131 chore: Allow dependabot to update ginkgo
  .github/dependabot.yml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1127 Update API version to `v1beta3`
  PROJECT
  api/v1beta3/groupversion_info.go
  api/v1beta3/ssp_types.go
  api/v1beta3/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/samples/kustomization.yaml
  config/samples/ssp_v1beta3_ssp.yaml
  config/webhook/manifests.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  docs/configuration.md
  hack/csv-generator.go
  internal/common/scheme.go
  tests/tests_suite_test.go
  tests/webhook_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta3/groupversion_info.go
  vendor/kubevirt.io/ssp-operator/api/v1beta3/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta3/zz_generated.deepcopy.go
  vendor/modules.txt
  webhooks/convert/convert.go
  webhooks/ssp_webhook.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1038 tests: Show clearer error message when cleanup tests fail
  tests/cleanup_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1136 feat: filter function tests with GINKGO_FOCUS environment variable
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1119 feat: validator: Load TLS configuration from ConfigMap
  internal/common/crypto_policy.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  internal/template-validator/filewatch/filewatch.go
  internal/template-validator/filewatch/filewatch_test.go
  internal/template-validator/tlsinfo/tlsinfo.go
  internal/template-validator/tlsinfo/tlsinfo_test.go
  internal/template-validator/validator/app.go
  tests/crypto_policy_test.go
  tests/validator_test.go
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#1143 test: enable end-to-end validator tests on s390x.
  tests/tests_suite_test.go
  tests/validator_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1147 Update common-templates bundle to version v0.29.4
  data/common-templates-bundle/common-templates-v0.29.4.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1146 tests: TLS policy: Use insecure TLS for connection to template-validator
  tests/crypto_policy_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved
