Repository kubevirt/ssp-operator, pull requests merged in 2024-04, with the labels that each got.

#938 bump-common-instancetypes.sh: Allow RC releases to be sync'd
  hack/bump-common-instancetypes.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#929 feat: Don't deploy tekton tasks and pipelines
  api/go.sum
  api/v1beta2/ssp_types.go
  automation/e2e-tekton/example-pipelines-test.sh
  automation/e2e-tekton/test-files/configmap.yaml
  automation/e2e-tekton/test-files/http-server.yaml
  automation/e2e-tekton/test-files/windows10-customize-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows10-dv.yaml
  automation/e2e-tekton/test-files/windows10-installer-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows11-customize-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows11-dv.yaml
  automation/e2e-tekton/test-files/windows11-installer-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows2k22-customize-pipelinerun.yaml
  automation/e2e-tekton/test-files/windows2k22-dv.yaml
  automation/e2e-tekton/test-files/windows2k22-installer-pipelinerun.yaml
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/rbac/role.yaml
  controllers/setup.go
  data/crd/ssp.kubevirt.io_ssps.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  data/tekton-pipelines/pipelines-rbac.yaml
  data/tekton-pipelines/windows-bios-installer-configmaps.yaml
  data/tekton-pipelines/windows-bios-installer-pipeline.yaml
  data/tekton-pipelines/windows-customize-configmaps.yaml
  data/tekton-pipelines/windows-customize-pipeline.yaml
  data/tekton-pipelines/windows-efi-installer-configmaps.yaml
  data/tekton-pipelines/windows-efi-installer-pipeline.yaml
  data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
  data/tekton-tasks/okd/kubevirt-tekton-tasks-okd.yaml
  internal/common/labels.go
  internal/common/owner.go
  internal/operands/data-sources/reconcile.go
  internal/operands/tekton-cleanup/reconcile.go
  internal/operands/tekton-cleanup/reconcile_test.go
  internal/operands/tekton-pipelines/reconcile.go
  internal/operands/tekton-pipelines/reconcile_test.go
  internal/operands/tekton-tasks/constants.go
  internal/operands/tekton-tasks/reconcile.go
  internal/operands/tekton-tasks/reconcile_test.go
  internal/tekton-bundle/tekton-bundle.go
  internal/tekton-bundle/tekton-bundle_test.go
  internal/tekton-bundle/test-bundle-files/test-pipelines/windows-installer.yaml
  internal/tekton-bundle/test-bundle-files/test-pipelines/windows-installer2-test.yaml
  internal/tekton-bundle/test-bundle-files/test-tasks/test-tasks.yaml
  tests/cleanup_test.go
  tests/tekton-cleanup_test.go
  tests/tekton-pipelines_test.go
  tests/tekton-tasks_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#942 [release-v0.19] CI: Fix kubevirt and CDI versions for this branch
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#944 [release-v0.18] CI: Fix kubevirt and CDI versions for this branch
  automation/common/versions.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#946 cleanup: Remove unused tekton and virtioImage code
  config/manager/manager.template.yaml
  config/samples/ssp_v1beta2_ssp.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  hack/csv-generator.go
  hack/csv-generator_test.go
  internal/common/environment.go
  internal/common/environment_test.go
  internal/common/labels.go
  internal/common/resource.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#945 docs: Remove invalid documentation
  README.md
  docs/configuration.md
  docs/development.md
  docs/installation.md
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#950 fix: Increase reconcile metric only if SSP CR was not changed
  controllers/ssp_controller.go
  internal/common/request.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#960 [release-v0.19] fix: Increase reconcile metric only if SSP CR was not changed
  controllers/ssp_controller.go
  internal/common/request.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#961 Add guest OS labels to cnv:vmi_status_running:count
  docs/metrics.md
  pkg/monitoring/rules/recordingrules/vmi.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#957 fix: Do not force IPv4 on metrics service
  controllers/services_controller.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
