Repository kubevirt/ssp-operator, pull requests merged in 2025-08, with the labels that each got.

#1459 feat: Deploy network policies
  automation/e2e-functests/run.sh
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  hack/csv-generator_test.go
  hack/install-network-policy.sh
  hack/sync.sh
  internal/common/resource.go
  internal/controllers/setup.go
  internal/networkpolicies/networkpolicies.go
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
  internal/operands/data-sources/resource.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/dataSources_test.go
  tests/validator_test.go
  tests/vm_console_proxy_test.go
Labels: dco-signoff: yes, release-note, size/XL, lgtm, approved

#1454 fix: Validate architectures in ".spec.cluster" in webhook
  tests/webhook_test.go
  webhooks/ssp_webhook.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1448 fix: clean up goroutines on error
  main.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved, ok-to-test

#1461 feat: Add support for multi-arch DataSources and DataImportCrons
  automation/common/versions.sh
  internal/architecture/architecture.go
  internal/architecture/architecture_test.go
  internal/controllers/setup.go
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/data-sources/constants.go
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
  internal/operands/data-sources/resource.go
  internal/template-bundle/bundle.go
  tests/commonTemplates_test.go
  tests/dataSources_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1469 fix(networkpolicies): Apply multiple fixes to network policies
  internal/networkpolicies/networkpolicies.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1471 Update resources of SSP and virt-template-validator
  config/manager/manager.template.yaml
  internal/operands/template-validator/resources.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1475 chore: Regenerate CSV
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1470 cleanup(template-validator): Listen on separate ports
  go.mod
  internal/networkpolicies/networkpolicies.go
  internal/operands/template-validator/resources.go
  internal/template-validator/service/service.go
  internal/template-validator/validator/app.go
  internal/template-validator/webhooks/hook.go
  tests/validator_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#1486 chore(deps): update module kubevirt.io/containerized-data-importer-api to v1.63.0
  api/go.mod
  api/go.sum
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/authorize_utils.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/authorize_utils.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1481 chore: update vm-console-proxy manifests to v0.9.0
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/defaults.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1488 ci: Use latest released CDI in CI
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1496 [release-v0.23] ci: Set kubevirt and CDI versions to specific minor versions
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1500 Remove the "Could not set vm volumes metrics" log
  internal/controllers/vm_controller.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1494 chore(deps): update module github.com/onsi/ginkgo/v2 to v2.24.0
  go.mod
  go.sum
  vendor/github.com/Masterminds/semver/v3/.gitignore
  vendor/github.com/Masterminds/semver/v3/.golangci.yml
  vendor/github.com/Masterminds/semver/v3/CHANGELOG.md
  vendor/github.com/Masterminds/semver/v3/LICENSE.txt
  vendor/github.com/Masterminds/semver/v3/Makefile
  vendor/github.com/Masterminds/semver/v3/README.md
  vendor/github.com/Masterminds/semver/v3/SECURITY.md
  vendor/github.com/Masterminds/semver/v3/collection.go
  vendor/github.com/Masterminds/semver/v3/constraints.go
  vendor/github.com/Masterminds/semver/v3/doc.go
  vendor/github.com/Masterminds/semver/v3/version.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/decorator_dsl.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/build/build_command.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo_t_dsl.go
  vendor/github.com/onsi/ginkgo/v2/internal/focus.go
  vendor/github.com/onsi/ginkgo/v2/internal/group.go
  vendor/github.com/onsi/ginkgo/v2/internal/node.go
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/internal/testingtproxy/testing_t_proxy.go
  vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/reporters/teamcity_report.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/errors.go
  vendor/github.com/onsi/ginkgo/v2/types/semver_filter.go
  vendor/github.com/onsi/ginkgo/v2/types/types.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#1495 [release-v0.24] ci: Set kubevirt and CDI versions to specific minor versions
  automation/common/versions.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1512 feat: Create PodDisruptionBudget for template validator
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  tests/validator_test.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved
