Repository kubevirt/ssp-operator, pull requests merged in 2025-09, with the labels that each got.

#1514 chore: Set port names according to convention
  config/default/manager_webhook_patch.yaml
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/metrics/resources.go
  internal/operands/template-validator/resources.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1527 tests: Improve test stability when deleting a template
  tests/validator_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1531 [release-v0.24] chore: Set port names according to convention
  config/default/manager_webhook_patch.yaml
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/metrics/resources.go
  internal/operands/template-validator/resources.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1529 feat: Add probes to operator and template validator
  config/manager/manager.template.yaml
  internal/operands/template-validator/resources.go
  main.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1553 chore: regenerated file using "make container-build"
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1543 chore(deps): update all dependencies
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/kubevirt.io/api/core/v1/types.go
  vendor/kubevirt.io/api/core/v1/types_swagger_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#1564 ci: Include bundle in check of generated files
  Makefile
  hack/check-commited-changes.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved
