Repository kubevirt/ssp-operator, pull requests merged in 2025-03, with the labels that each got.

#1307 chore(deps): Bump the production-dependencies group across 1 director…
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/net/internal/httpcommon/headermap.go
  api/vendor/golang.org/x/net/internal/httpcommon/request.go
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1268 [release-v0.16] deps: Update golang version to 1.19
  .github/workflows/pull-request.yaml
  Dockerfile
  api/go.mod
  go.mod
  validator.Dockerfile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, needs-approver-review

#1312 chore(golangci-lint): Bump golangci-lint 1.64.6
  Makefile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1311 chore(deps): Bump sigs.k8s.io/controller-runtime
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1324 Update common-templates to v0.33.0
  data/common-templates-bundle/common-templates-amd64-v0.33.0.yaml
  data/common-templates-bundle/common-templates-s390x-v0.33.0.yaml
  data/common-templates-bundle/common-templates-v0.33.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1325 chore(deps): Bump the production-dependencies group across 1 directory with 2 updates
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1329 tests: fix race when checking recreated resources
  tests/tests_common_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1332 chore(vm-delete-protection): Improve error message
  internal/operands/vm-delete-protection/resources.go
  tests/vm_delete_protection_test.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1278 cleanup: Fix various issues found by code inspection
  api/v1beta2/ssp_types.go
  hack/csv-generator.go
  internal/common/labels_test.go
  internal/common/resource.go
  internal/common/resource_test.go
  internal/common/scheme.go
  internal/controllers/ssp_controller.go
  internal/controllers/webhook_controller.go
  internal/env/env_test.go
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/template-validator/resources.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/template-validator/kubevirtjobs/virtualmachine.go
  internal/template-validator/labels/labels.go
  internal/template-validator/tlsinfo/tlsinfo.go
  internal/template-validator/validation/eval.go
  internal/template-validator/validation/eval_test.go
  internal/template-validator/validation/path/conv.go
  internal/template-validator/validator/app.go
  internal/template-validator/webhooks/utils.go
  main.go
  pkg/monitoring/metrics/template-validator/metrics.go
  tests/crypto_policy_test.go
  tests/labels_test.go
  tests/metrics_test_utils.go
  tests/misc_test.go
  tests/port-forwarding.go
  tests/validator_test.go
  tests/vm_console_proxy_test.go
  tests/watcher.go
  tools/test-rules-writer/test_rules_writer.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1343 Update common-templates to v0.34.0
  data/common-templates-bundle/common-templates-amd64-v0.34.0.yaml
  data/common-templates-bundle/common-templates-arm64-v0.34.0.yaml
  data/common-templates-bundle/common-templates-s390x-v0.34.0.yaml
  data/common-templates-bundle/common-templates-v0.34.0.yaml
  internal/operands/common-templates/version.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved
