Repository kubevirt/ssp-operator, pull requests merged in 2025-01, with the labels that each got.

#1204 tests: Increase timeout waiting for SSP deployment to be ready.
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1210 feat: disable renovate's regular dependency updates
  renovate.json
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1211 feat: Update golang version to 1.23.2
  Dockerfile
  api/go.mod
  ci-builder/Dockerfile
  go.mod
  validator.Dockerfile
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1201 refactor: use the template architecture label
  internal/template-bundle/bundle.go
  internal/template-bundle/template-bundle-test.yaml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1199 feat: Add VM delete protection
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  go.mod
  internal/common/labels.go
  internal/controllers/setup.go
  internal/operands/vm-delete-protection/reconcile.go
  internal/operands/vm-delete-protection/reconcile_test.go
  internal/operands/vm-delete-protection/resources.go
  tests/cleanup_test.go
  tests/vm_delete_protection_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#1218 Add dependabot configuration for api
  .github/dependabot.yml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1216 docs: Add vm-delete-protection operand
  README.md
  docs/development.md
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1222 deps: Updates controller-tools version
  Makefile
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  config/rbac/role.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#1212 doc: Update disclaimer in readTemplates
  internal/template-bundle/bundle.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1223 doc: common instancetypes are not released to the SSP
  README.md
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1231 feat: Improve errors returned from reconciliation
  internal/common/resource.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1234 chore(deps): Bump sigs.k8s.io/controller-runtime
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/priorityqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1139 chore: Remove custom reporters from functional tests
  go.mod
  go.sum
  tests/tests_suite_test.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XL, release-note-none, lgtm, approved

#1235 Remove common-instancetypes support
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  docs/development.md
  docs/installation.md
  hack/bump-common-instancetypes.sh
  hack/sync.sh
  internal/common/resource.go
  internal/common/scheme.go
  internal/controllers/setup.go
  internal/operands/common-instancetypes/reconcile.go
  internal/operands/common-instancetypes/reconcile_test.go
  tests/common_instancetypes_test.go
  tests/tests_suite_test.go
  vendor/kubevirt.io/api/instancetype/OWNERS
  vendor/kubevirt.io/api/instancetype/register.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/conversion.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/deepcopy_generated.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/doc.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/register.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/types.go
  vendor/kubevirt.io/api/instancetype/v1alpha2/types_swagger_generated.go
  vendor/kubevirt.io/api/instancetype/v1beta1/deepcopy_generated.go
  vendor/kubevirt.io/api/instancetype/v1beta1/doc.go
  vendor/kubevirt.io/api/instancetype/v1beta1/register.go
  vendor/kubevirt.io/api/instancetype/v1beta1/types.go
  vendor/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1219 chore: Improve release automation
  .github/workflows/create-release-branch.yaml
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1241 [release-v0.22] CI: Fix kubevirt and CDI versions
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1237 chore(CI): Improve uncommited files vebosity
  hack/check-commited-changes.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1244 chore(test): Add cleanup in VM delete protection test
  tests/vm_delete_protection_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1256 fix: regex in renovate config
  renovate.json
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1242 [release-v0.21] CI: Fix CDI version
  automation/common/versions.sh
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
