Repository kubevirt/ssp-operator, pull requests merged in 2025-07, with the labels that each got.

#1426 chore(update-go): Update go version to 1.24.3
  Dockerfile
  api/go.mod
  go.mod
  validator.Dockerfile
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1431 chore(deps): Bump the production-dependencies group across 1 directory with 17 updates
  go.mod
  go.sum
  vendor/github.com/google/gnostic-models/compiler/context.go
  vendor/github.com/google/gnostic-models/compiler/extensions.go
  vendor/github.com/google/gnostic-models/compiler/helpers.go
  vendor/github.com/google/gnostic-models/compiler/reader.go
  vendor/github.com/google/gnostic-models/jsonschema/models.go
  vendor/github.com/google/gnostic-models/jsonschema/reader.go
  vendor/github.com/google/gnostic-models/jsonschema/writer.go
  vendor/github.com/google/gnostic-models/openapiv2/OpenAPIv2.go
  vendor/github.com/google/gnostic-models/openapiv2/document.go
  vendor/github.com/google/gnostic-models/openapiv3/OpenAPIv3.go
  vendor/github.com/google/gnostic-models/openapiv3/document.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/meminfo.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/proc_statm.go
  vendor/github.com/stoewer/go-strcase/.golangci.yml
  vendor/github.com/stoewer/go-strcase/camel.go
  vendor/github.com/stoewer/go-strcase/helper.go
  vendor/go.yaml.in/yaml/v3/LICENSE
  vendor/go.yaml.in/yaml/v3/NOTICE
  vendor/go.yaml.in/yaml/v3/README.md
  vendor/go.yaml.in/yaml/v3/apic.go
  vendor/go.yaml.in/yaml/v3/decode.go
  vendor/go.yaml.in/yaml/v3/emitterc.go
  vendor/go.yaml.in/yaml/v3/encode.go
  vendor/go.yaml.in/yaml/v3/parserc.go
  vendor/go.yaml.in/yaml/v3/readerc.go
  vendor/go.yaml.in/yaml/v3/resolve.go
  vendor/go.yaml.in/yaml/v3/scannerc.go
  vendor/go.yaml.in/yaml/v3/sorter.go
  vendor/go.yaml.in/yaml/v3/writerc.go
  vendor/go.yaml.in/yaml/v3/yaml.go
  vendor/go.yaml.in/yaml/v3/yamlh.go
  vendor/go.yaml.in/yaml/v3/yamlprivateh.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/google.golang.org/genproto/googleapis/api/expr/v1alpha1/checked.pb.go
  vendor/google.golang.org/genproto/googleapis/api/expr/v1alpha1/eval.pb.go
  vendor/google.golang.org/genproto/googleapis/api/expr/v1alpha1/explain.pb.go
  vendor/google.golang.org/genproto/googleapis/api/expr/v1alpha1/syntax.pb.go
  vendor/google.golang.org/genproto/googleapis/api/expr/v1alpha1/value.pb.go
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document_v3.go
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#1449 deps: Update CDI API version to v1.63.0-alpha.0
  api/go.mod
  api/go.sum
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  api/vendor/modules.txt
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  go.mod
  go.sum
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1450 api: Add new fields for multi-arch support
  api/v1beta3/ssp_types.go
  api/v1beta3/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  tests/webhook_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta3/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta3/zz_generated.deepcopy.go
  webhooks/ssp_webhook.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved

#1442 chore(deps): Bump the production-dependencies group across 1 directory with 4 updates
  api/go.mod
  api/go.sum
  api/vendor/github.com/fxamacker/cbor/v2/README.md
  api/vendor/github.com/fxamacker/cbor/v2/cache.go
  api/vendor/github.com/fxamacker/cbor/v2/common.go
  api/vendor/github.com/fxamacker/cbor/v2/decode.go
  api/vendor/github.com/fxamacker/cbor/v2/encode.go
  api/vendor/github.com/fxamacker/cbor/v2/structfields.go
  api/vendor/github.com/fxamacker/cbor/v2/tag.go
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/github.com/fxamacker/cbor/v2/README.md
  vendor/github.com/fxamacker/cbor/v2/cache.go
  vendor/github.com/fxamacker/cbor/v2/common.go
  vendor/github.com/fxamacker/cbor/v2/decode.go
  vendor/github.com/fxamacker/cbor/v2/encode.go
  vendor/github.com/fxamacker/cbor/v2/structfields.go
  vendor/github.com/fxamacker/cbor/v2/tag.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#1418 feat: Add common templates for heterogeneous clusters
  internal/architecture/architecture.go
  internal/controllers/setup.go
  internal/operands/common-templates/architecture.go
  internal/operands/common-templates/architecture_test.go
  internal/operands/common-templates/common_templates_suite_test.go
  internal/operands/common-templates/constants.go
  internal/operands/common-templates/reconcile.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
  internal/operands/data-sources/resource.go
  internal/template-bundle/bundle.go
  internal/template-bundle/bundle_test.go
  tests/commonTemplates_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, size/XXL, release-note, lgtm, approved

#1458 Add NetworkPolicies required by SSP
  Makefile
  config/default/kustomization.yaml
  config/hco-network-policy/hco_allow_egress_to_api_server.yaml
  config/hco-network-policy/k8s_hco-allow-egress-to-dns.yaml
  config/hco-network-policy/kustomization.yaml
  config/hco-network-policy/ocp_hco-allow-egress-to-dns.yaml
  config/manager/manager.template.yaml
  config/network-policy/allow_ingress_to_ssp_operator_webhook_and_metrics.yaml
  config/network-policy/kustomization.yaml
  data/network-policy/allow_ingress_to_ssp_operator_webhook_and_metrics.yaml
  hack/csv-generator.go
Labels: dco-signoff: yes, size/L, release-note, lgtm, approved
