Repository kubevirt/ssp-operator, pull requests merged in 2025-06, with the labels that each got.

#1407 fix: Add delete permission to PrometheusRules and ServiceMonitors
  config/rbac/role.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/data-sources/reconcile.go
  internal/operands/metrics/reconcile.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved

#1405 api: deprecate v1beta2 and use v1beta3
  api/v1beta2/ssp_types.go
  api/v1beta3/ssp_types.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  internal/common/labels.go
  internal/common/labels_test.go
  internal/common/owner_test.go
  internal/common/request.go
  internal/common/resource_test.go
  internal/controller/predicates/predicates_test.go
  internal/controllers/ssp_controller.go
  internal/controllers/webhook_controller.go
  internal/controllers/webhook_controller_test.go
  internal/operands/common-templates/reconcile_test.go
  internal/operands/data-sources/reconcile.go
  internal/operands/data-sources/reconcile_test.go
  internal/operands/metrics/reconcile_test.go
  internal/operands/template-validator/reconcile.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/vm-console-proxy/reconcile_test.go
  internal/operands/vm-delete-protection/reconcile_test.go
  main.go
  tests/cleanup_test.go
  tests/commonTemplates_test.go
  tests/crypto_policy_test.go
  tests/dataSources_test.go
  tests/misc_test.go
  tests/monitoring_test.go
  tests/single_node_test.go
  tests/tests_common_test.go
  tests/tests_suite_test.go
  tests/validator_test.go
  tests/vm_console_proxy_test.go
  tests/watcher.go
  tests/webhook_controller_test.go
  tests/webhook_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta2/ssp_types.go
  vendor/kubevirt.io/ssp-operator/api/v1beta3/ssp_types.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1413 Bump Go to 1.23.8
  Dockerfile
  ci-builder/Dockerfile
  go.mod
  validator.Dockerfile
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved, needs-ok-to-test

#1414 chore: Update webhook code to use SSP v1beta3
  webhooks/convert/convert.go
  webhooks/ssp_webhook.go
  webhooks/ssp_webhook_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved
