Repository kubevirt/ssp-operator, pull requests merged in 2025-02, with the labels that each got.

#1269 cleanup: Remove code for updating from very old kubevirt-ssp-operator
  internal/controllers/ssp_controller.go
  tests/upgrade_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1276 chore(deps): Bump the production-dependencies group across 1 directory with 3 updates
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/priorityqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1277 cleanup: Remove net.Pipe in port-forwarding in functests
  tests/port-forwarding.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1281 tests: Improve stability of metric tests
  tests/commonTemplates_test.go
  tests/metrics_test.go
  tests/metrics_test_utils.go
  tests/misc_test.go
  tests/port-forwarding.go
  tests/tests_common_test.go
  tests/validator_test.go
Labels: dco-signoff: yes, size/L, release-note-none, lgtm, approved

#1282 feat: Set "openshift.io/required-scc" annotation on deployments
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/common/labels.go
  internal/operands/template-validator/reconcile_test.go
  internal/operands/template-validator/resources.go
  internal/operands/vm-console-proxy/reconcile.go
  internal/operands/vm-console-proxy/reconcile_test.go
  tests/scc_annotation_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1126 [release-v0.18] Alert VMStorageClassWarning only for Windows VMs
  internal/operands/metrics/resources.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1285 Alert VMStorageClassWarning only for Windows VMs
  internal/operands/metrics/resources.go
  tests/monitoring_test.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1290 [release-v0.21] api: set v1beta1 version to not be served
  api/v1beta1/ssp_types.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  tests/webhook_test.go
  vendor/kubevirt.io/ssp-operator/api/v1beta1/ssp_types.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#1291 [release-v0.22] fix: Add back API v1beta1 and set it to not be served
  PROJECT
  api/v1beta1/groupversion_info.go
  api/v1beta1/ssp_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved
