Repository kubevirt/ssp-operator, pull requests merged in 2025-05, with the labels that each got.

#1379 [release-v0.23] chore: update vm-console-proxy manifests to v0.8.1
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/defaults.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1380 [release-v0.22] chore: update vm-console-proxy manifests to v0.8.1
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/defaults.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1378 chore: update vm-console-proxy manifests to v0.8.1
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/defaults.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1381 [release-v0.21] chore: update vm-console-proxy manifests to v0.6.2
  data/vm-console-proxy-bundle/vm-console-proxy.yaml
  internal/operands/vm-console-proxy/defaults.go
Labels: dco-signoff: yes, size/XS, release-note, lgtm, approved

#1386 Add polarion test id's
  tests/vm_delete_protection_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1240 tests: Set DICT RetentionPolicy to None
  tests/dataSources_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1394 [release-v0.18] tests: Set DICT RetentionPolicy to None
  tests/dataSources_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1401 tests: fix: Incorrect Eventually block in expectRestoreAfterUpdate()
  tests/tests_common_test.go
Labels: dco-signoff: yes, size/XS, release-note-none, lgtm, approved
