Repository kubevirt/ssp-operator, pull requests merged in 2025-04, with the labels that each got.

#1346 deps: Update golang and monitoring-linter
  Dockerfile
  Makefile
  ci-builder/Dockerfile
  go.mod
  validator.Dockerfile
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1347 deps: Update OpenShift dependencies to latest "release-4.18" branch
  api/go.mod
  api/go.sum
  api/vendor/github.com/openshift/api/config/v1/types.go
  api/vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  api/vendor/github.com/openshift/api/config/v1/types_feature.go
  api/vendor/github.com/openshift/api/config/v1/types_image.go
  api/vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  api/vendor/github.com/openshift/api/config/v1/types_network.go
  api/vendor/github.com/openshift/api/config/v1/types_node.go
  api/vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  api/vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  api/vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  api/vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  api/vendor/modules.txt
  config/crd/bases/ssp.kubevirt.io_ssps.yaml
  data/crd/ssp.kubevirt.io_ssps.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/types_tlssecurityprofile.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/template/v1/generated.proto
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#1350 feat(CNV-58257): set terminationMessagePolicy in all containers
  config/manager/manager.template.yaml
  data/olm-catalog/ssp-operator.clusterserviceversion.yaml
  internal/operands/template-validator/resources.go
  internal/operands/vm-console-proxy/reconcile.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#1356 fix: vm_controller: Don't fail if PVC or PV does not exist
  internal/controllers/vm_controller.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#1359 chore(deps): Bump the production-dependencies group across 1 directory with 5 updates
  api/go.mod
  api/go.sum
  api/vendor/github.com/fxamacker/cbor/v2/README.md
  api/vendor/github.com/fxamacker/cbor/v2/bytestring.go
  api/vendor/github.com/fxamacker/cbor/v2/cache.go
  api/vendor/github.com/fxamacker/cbor/v2/decode.go
  api/vendor/github.com/fxamacker/cbor/v2/doc.go
  api/vendor/github.com/fxamacker/cbor/v2/encode.go
  api/vendor/github.com/fxamacker/cbor/v2/encode_map.go
  api/vendor/github.com/fxamacker/cbor/v2/encode_map_go117.go
  api/vendor/github.com/fxamacker/cbor/v2/omitzero_go124.go
  api/vendor/github.com/fxamacker/cbor/v2/omitzero_pre_go124.go
  api/vendor/github.com/fxamacker/cbor/v2/simplevalue.go
  api/vendor/github.com/fxamacker/cbor/v2/stream.go
  api/vendor/github.com/fxamacker/cbor/v2/structfields.go
  api/vendor/github.com/fxamacker/cbor/v2/tag.go
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  api/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  api/vendor/modules.txt
  api/vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  api/vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/validate.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
Labels: dco-signoff: yes, size/XXL, release-note-none, lgtm, approved

#1369 fix: subset of enabled architectures for running e2e tests
  tests/tests_suite_test.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved
